#!/usr/bin/env bash
# NodeMap — One-shot setup script
# Usage: bash setup.sh

set -euo pipefail

BOLD="\033[1m"
GREEN="\033[32m"
CYAN="\033[36m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

echo ""
echo -e "${BOLD}${CYAN}⬡  NodeMap Setup${RESET}"
echo "────────────────────────────────────────"

# ── Prereq check ──────────────────────────────────────────────
echo -e "\n${BOLD}Checking prerequisites...${RESET}"
for cmd in docker openssl; do
  if command -v "$cmd" &>/dev/null; then
    echo -e "  ${GREEN}✓${RESET} $cmd"
  else
    echo -e "  ${RED}✗${RESET} $cmd not found. Please install it first."
    exit 1
  fi
done

if docker compose version &>/dev/null 2>&1; then
  echo -e "  ${GREEN}✓${RESET} docker compose"
else
  echo -e "  ${RED}✗${RESET} docker compose plugin not found."
  exit 1
fi

# ── .env ──────────────────────────────────────────────────────
echo -e "\n${BOLD}Configuring environment...${RESET}"

if [ -f .env ]; then
  echo -e "  ${YELLOW}!${RESET} .env already exists, skipping generation."
else
  echo -e "  Generating secrets..."
  ACCESS_SECRET=$(openssl rand -hex 64)
  REFRESH_SECRET=$(openssl rand -hex 64)
  PG_PASS=$(openssl rand -hex 24)
  REDIS_PASS=$(openssl rand -hex 24)

  read -p "  Admin email [admin@nodemap.local]: " ADMIN_EMAIL
  ADMIN_EMAIL=${ADMIN_EMAIL:-admin@nodemap.local}

  read -sp "  Admin password (min 12 chars): " ADMIN_PASS
  echo
  if [ ${#ADMIN_PASS} -lt 12 ]; then
    echo -e "  ${RED}Password too short, using generated one.${RESET}"
    ADMIN_PASS=$(openssl rand -hex 12)
    echo -e "  Generated admin password: ${BOLD}${ADMIN_PASS}${RESET}"
  fi

  read -p "  Your domain/IP for CORS [http://localhost]: " CORS_ORIGIN
  CORS_ORIGIN=${CORS_ORIGIN:-http://localhost}

  cat > .env <<EOF
# ── Generated by setup.sh ──────────────────────────────────
POSTGRES_DB=nodemap
POSTGRES_USER=nodemap
POSTGRES_PASSWORD=${PG_PASS}

REDIS_PASSWORD=${REDIS_PASS}

JWT_ACCESS_SECRET=${ACCESS_SECRET}
JWT_REFRESH_SECRET=${REFRESH_SECRET}
JWT_ACCESS_EXPIRES=15m
JWT_REFRESH_EXPIRES=7d

BCRYPT_ROUNDS=12
CORS_ORIGIN=${CORS_ORIGIN}

HTTP_PORT=80
HTTPS_PORT=443

ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASS}

REGISTRATION_OPEN=false
EOF
  echo -e "  ${GREEN}✓${RESET} .env created"
fi

# ── TLS Certs ─────────────────────────────────────────────────
echo -e "\n${BOLD}TLS certificates...${RESET}"
mkdir -p nginx/certs

if [ -f nginx/certs/cert.pem ] && [ -f nginx/certs/key.pem ]; then
  echo -e "  ${YELLOW}!${RESET} Certificates already exist, skipping."
else
  echo -e "  Generating self-signed certificate (3650 days)..."
  openssl req -x509 -newkey rsa:4096 \
    -keyout nginx/certs/key.pem \
    -out nginx/certs/cert.pem \
    -days 3650 -nodes \
    -subj "/CN=nodemap.local" 2>/dev/null
  chmod 600 nginx/certs/key.pem
  echo -e "  ${GREEN}✓${RESET} Self-signed cert generated"
  echo -e "  ${YELLOW}Tip:${RESET} Replace with a real cert for production (see README)"
fi

# ── Launch ────────────────────────────────────────────────────
echo -e "\n${BOLD}Starting NodeMap...${RESET}"
docker compose pull --quiet 2>/dev/null || true
docker compose up -d --build

echo ""
echo -e "${BOLD}${GREEN}────────────────────────────────────────${RESET}"
echo -e "${BOLD}${GREEN}  ✓ NodeMap is up!${RESET}"
echo -e "${BOLD}${GREEN}────────────────────────────────────────${RESET}"
echo ""
echo -e "  URL:   ${CYAN}https://localhost${RESET}  (or your server IP)"
echo -e "  Email: ${CYAN}$(grep ADMIN_EMAIL .env | cut -d= -f2)${RESET}"
echo ""
echo -e "  ${YELLOW}Tip:${RESET} Your browser will warn about the self-signed cert."
echo -e "        Accept it, or add it to your trusted store."
echo ""
echo -e "  Useful commands:"
echo -e "    make logs       — tail all logs"
echo -e "    make backup     — backup the database"
echo -e "    make shell-db   — open psql"
echo -e "    make health     — check /health"
echo -e "    make deploy     — pull latest code + rebuild + health-check"
echo ""
