/**
 * DocExportModal — exports a NoNote map as a Word (.docx) document.
 *
 * Two modes:
 *  "normal" — structured interpretation of the canvas as documentation:
 *             headings, node descriptions, notes, connection table.
 *  "ai"     — sends the map data to the connected LLM which interprets
 *             it into meaningful prose documentation, then generates docx.
 *
 * The docx is generated client-side via the docx npm package loaded from CDN.
 */

import { useState, useEffect } from "react";
import { apiFetch } from "../api/client.js";

const NT_LABELS = {
  note:"Note", heading:"Heading", user:"User", process:"Process", decision:"Decision",
  router:"Router", switch:"Switch", firewall:"Firewall", server:"Server",
  webserver:"Web Server", database:"Database", api:"API", service:"Service",
  cloud:"Cloud", container:"Container", k8s:"Kubernetes", microservice:"Microservice",
};

// ── Build docx via CDN-loaded library ──────────────────────────────────────
async function buildDocx(title, sections) {
  // Load docx from CDN
  if (!window.docx) {
    await new Promise((res, rej) => {
      const s = document.createElement("script");
      s.src = "https://cdnjs.cloudflare.com/ajax/libs/docx/8.5.0/docx.umd.min.js";
      s.onload = res; s.onerror = rej;
      document.head.appendChild(s);
    });
  }
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
          BorderStyle, ShadingType, Table, TableRow, TableCell, WidthType } = window.docx;

  const border = { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" };
  const borders = { top:border, bottom:border, left:border, right:border };

  const children = [
    // Title
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: title, bold: true, size: 48 })],
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Generated by NoNote · ${new Date().toLocaleDateString("en-GB", { dateStyle: "long" })}`,
        color: "888888", size: 18, italics: true,
      })],
      spacing: { after: 400 },
    }),
  ];

  for (const sec of sections) {
    if (sec.type === "h1") {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: sec.text, bold: true, size: 28 })],
        spacing: { before: 400, after: 160 },
      }));
    } else if (sec.type === "h2") {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: sec.text, bold: true, size: 24 })],
        spacing: { before: 280, after: 120 },
      }));
    } else if (sec.type === "p") {
      children.push(new Paragraph({
        children: [new TextRun({ text: sec.text, size: 22 })],
        spacing: { after: 120 },
      }));
    } else if (sec.type === "label") {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: sec.label + ": ", bold: true, size: 22 }),
          new TextRun({ text: sec.value, size: 22 }),
        ],
        spacing: { after: 80 },
      }));
    } else if (sec.type === "note") {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: "📝 ", size: 20 }),
          new TextRun({ text: sec.text, size: 20, color: "444444", italics: true }),
        ],
        indent: { left: 720 },
        spacing: { after: 80 },
        border: { left: { style: BorderStyle.SINGLE, size: 6, color: "58A6FF" } },
      }));
    } else if (sec.type === "divider") {
      children.push(new Paragraph({
        children: [new TextRun({ text: "" })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "EEEEEE" } },
        spacing: { after: 200 },
      }));
    } else if (sec.type === "table") {
      const colW = Math.floor(9360 / sec.headers.length);
      children.push(new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: sec.headers.map(() => colW),
        rows: [
          // Header row
          new TableRow({
            tableHeader: true,
            children: sec.headers.map(h => new TableCell({
              borders,
              shading: { fill: "1F3A5F", type: ShadingType.CLEAR },
              width: { size: colW, type: WidthType.DXA },
              margins: { top: 80, bottom: 80, left: 120, right: 120 },
              children: [new Paragraph({
                children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })],
              })],
            })),
          }),
          // Data rows
          ...sec.rows.map((row, ri) => new TableRow({
            children: row.map(cell => new TableCell({
              borders,
              shading: { fill: ri % 2 === 0 ? "F8F9FA" : "FFFFFF", type: ShadingType.CLEAR },
              width: { size: colW, type: WidthType.DXA },
              margins: { top: 60, bottom: 60, left: 120, right: 120 },
              children: [new Paragraph({
                children: [new TextRun({ text: String(cell || ""), size: 20 })],
              })],
            })),
          })),
        ],
      }));
      children.push(new Paragraph({ children: [new TextRun("")], spacing: { after: 200 } }));
    }
  }

  const doc = new Document({
    styles: {
      default: { document: { run: { font: "Calibri", size: 22 } } },
    },
    sections: [{
      properties: {
        page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      children,
    }],
  });

  return Packer.toBlob(doc);
}

// ── Normal mode: structured interpretation ─────────────────────────────────
function buildNormalSections(nodes, edges, title) {
  const sections = [];

  // Group nodes by type category
  const byType = {};
  nodes.forEach(n => {
    const cat = n.type || "note";
    if (!byType[cat]) byType[cat] = [];
    byType[cat].push(n);
  });

  sections.push({ type: "h1", text: "Overview" });
  sections.push({ type: "p", text: `This document describes the "${title}" diagram containing ${nodes.length} components and ${edges.length} connections.` });
  sections.push({ type: "divider" });

  // Nodes grouped by category
  const usedTypes = [...new Set(nodes.map(n => n.type || "note"))];
  sections.push({ type: "h1", text: "Components" });

  usedTypes.forEach(type => {
    const group = byType[type];
    const label = NT_LABELS[type] || type;
    sections.push({ type: "h2", text: `${label} (${group.length})` });
    group.forEach(node => {
      sections.push({ type: "h2", text: node.title || "Untitled" });
      if (node.description) {
        sections.push({ type: "p", text: node.description });
      }
      sections.push({ type: "label", label: "Type", value: label });
      // Notes
      const notes = Array.isArray(node.notes) ? node.notes.filter(n => !n.sensitive) : [];
      if (notes.length > 0) {
        sections.push({ type: "label", label: "Notes", value: "" });
        notes.forEach(note => {
          const text = typeof note === "string" ? note : (note.content || "");
          if (text) sections.push({ type: "note", text });
        });
      }
      // Custom properties
      const props = Object.entries(node.properties || {}).filter(([, v]) => v);
      props.forEach(([k, v]) => {
        sections.push({ type: "label", label: k, value: String(v) });
      });
      sections.push({ type: "divider" });
    });
  });

  // Connections table
  if (edges.length > 0) {
    sections.push({ type: "h1", text: "Connections" });
    const nodeMap = Object.fromEntries(nodes.map(n => [n.id, n]));
    sections.push({
      type: "table",
      headers: ["From", "To", "Label", "Style"],
      rows: edges.map(e => [
        nodeMap[e.from]?.title || e.from,
        nodeMap[e.to]?.title || e.to,
        e.label || "—",
        e.style || "arrow",
      ]),
    });
  }

  return sections;
}

// ── Build LLM prompt from map data ─────────────────────────────────────────
function buildLLMPrompt(nodes, edges, title) {
  const nodeMap = Object.fromEntries(nodes.map(n => [n.id, n]));
  const lines = [
    `You are a technical documentation writer. Convert the following NoNote diagram into a well-structured Word document in professional documentation style.`,
    `The map is titled: "${title}"`,
    ``,
    `Nodes (${nodes.length} total):`,
    ...nodes.map(n => {
      const notes = Array.isArray(n.notes) ? n.notes.filter(x => !x.sensitive).map(x => typeof x === "string" ? x : x.content).filter(Boolean) : [];
      return `- [${(NT_LABELS[n.type] || n.type).toUpperCase()}] ${n.title}${n.description ? `: ${n.description}` : ""}${notes.length ? ` | Notes: ${notes.join("; ")}` : ""}`;
    }),
    ``,
    `Connections (${edges.length} total):`,
    ...edges.map(e => `- ${nodeMap[e.from]?.title || "?"} → ${nodeMap[e.to]?.title || "?"}${e.label ? ` (${e.label})` : ""}`),
    ``,
    `Write a professional technical document with:`,
    `1. An executive summary paragraph explaining what this system/diagram represents`,
    `2. A detailed section for each logical group of components`,
    `3. A connections/relationships section explaining the data/control flow`,
    `4. A conclusion or recommendations section`,
    ``,
    `Format your response as a JSON array of sections. Each section is an object with:`,
    `{"type": "h1"|"h2"|"p"|"note"|"divider", "text": "content"}`,
    ``,
    `Respond ONLY with the JSON array, no other text or markdown.`,
  ];
  return lines.join("\n");
}

export default function DocExportModal({ nodes, edges, mapTitle, mode, onClose }) {
  const [status,   setStatus]   = useState("idle"); // idle | generating | done | error
  const [progress, setProgress] = useState("");
  const [aiProviders, setAiProviders] = useState([]);
  const [selectedProvider, setSelectedProvider] = useState("");

  useEffect(() => {
    if (mode === "ai") {
      apiFetch("/llm/providers").then(d => {
        const providers = Array.isArray(d) ? d : (d.providers || []);
        setAiProviders(providers);
        if (providers.length > 0) setSelectedProvider(providers[0].id);
      }).catch(() => {});
    }
  }, [mode]);

  const doExport = async () => {
    setStatus("generating");
    try {
      let sections;

      if (mode === "normal") {
        setProgress("Building document structure…");
        sections = buildNormalSections(nodes, edges, mapTitle);
      } else {
        // AI mode — ask the LLM to interpret
        setProgress("Sending map to AI for interpretation…");
        const prompt = buildLLMPrompt(nodes, edges, mapTitle);

        const response = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: "claude-sonnet-4-20250514",
            max_tokens: 4000,
            messages: [{ role: "user", content: prompt }],
          }),
        });

        if (!response.ok) {
          // Fall back to backend LLM if direct Anthropic fails
          setProgress("Using configured LLM provider…");
          const backendResp = await apiFetch("/llm/chat", {
            method: "POST",
            body: JSON.stringify({
              providerId: selectedProvider,
              message: prompt,
            }),
          });
          const text = backendResp.response || backendResp.content || "";
          const clean = text.replace(/```json\n?|```/g, "").trim();
          sections = JSON.parse(clean);
        } else {
          const data = await response.json();
          const text = data.content?.[0]?.text || "";
          const clean = text.replace(/```json\n?|```/g, "").trim();
          sections = JSON.parse(clean);
        }

        setProgress("AI response received, generating document…");
      }

      setProgress("Building Word document…");
      const blob = await buildDocx(mapTitle, sections);

      // Download
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${(mapTitle || "map").replace(/[^a-z0-9]/gi, "-")}-${mode === "ai" ? "ai-" : ""}docs.docx`;
      a.click();
      URL.revokeObjectURL(url);

      setStatus("done");
      setProgress("Document downloaded!");
    } catch (err) {
      console.error("[DocExport]", err);
      setStatus("error");
      setProgress(err.message || "Export failed");
    }
  };

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 900,
      background: "rgba(0,0,0,.72)", display: "flex", alignItems: "center", justifyContent: "center" }}
      onClick={onClose}>
      <div onClick={e => e.stopPropagation()}
        style={{ background: "var(--bg2)", border: "1.5px solid var(--border)",
          borderRadius: 14, boxShadow: "0 24px 72px rgba(0,0,0,.7)",
          width: "min(480px, 94vw)", padding: 28, display: "flex", flexDirection: "column", gap: 18 }}>

        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ fontSize: 22 }}>{mode === "ai" ? "🤖" : "📄"}</span>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 15, fontWeight: 700, color: "var(--text)" }}>
              {mode === "ai" ? "AI-Interpreted" : "Standard"} Word Export
            </div>
            <div style={{ fontSize: 11, color: "var(--text4)", marginTop: 2 }}>
              {mode === "ai"
                ? "LLM reads and interprets your map into professional documentation"
                : "Structured documentation built directly from your nodes, notes, and connections"}
            </div>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none",
            fontSize: 22, color: "var(--text4)", cursor: "pointer" }}>×</button>
        </div>

        {/* Mode description */}
        <div style={{ background: "var(--bg3)", borderRadius: 8, padding: "12px 16px",
          border: `1px solid ${mode === "ai" ? "var(--accent)40" : "var(--border)"}` }}>
          {mode === "normal" ? (
            <div style={{ fontSize: 12, color: "var(--text3)", lineHeight: 1.6 }}>
              <strong style={{ color: "var(--text)" }}>What you'll get:</strong><br/>
              • Title page with map name and export date<br/>
              • Components section — each node with title, type, description, notes, properties<br/>
              • Connections table showing all relationships<br/>
              • Proper Word headings, bullet points, and styling
            </div>
          ) : (
            <div style={{ fontSize: 12, color: "var(--text3)", lineHeight: 1.6 }}>
              <strong style={{ color: "var(--text)" }}>What the AI will do:</strong><br/>
              • Read your entire map — all nodes, connections, notes<br/>
              • Interpret the architecture/system and write meaningful prose<br/>
              • Structure it as professional documentation with executive summary<br/>
              • Group related components logically, explain data flows
            </div>
          )}
        </div>

        {/* AI provider selector */}
        {mode === "ai" && aiProviders.length > 0 && (
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: "var(--text4)", letterSpacing: 1.5, marginBottom: 6 }}>
              LLM PROVIDER
            </div>
            <select value={selectedProvider} onChange={e => setSelectedProvider(e.target.value)}
              style={{ width: "100%", background: "var(--bg3)", border: "1px solid var(--border)",
                borderRadius: 8, padding: "8px 12px", color: "var(--text)", fontSize: 13,
                fontFamily: "var(--font-ui)", outline: "none" }}>
              {aiProviders.map(p => (
                <option key={p.id} value={p.id}>{p.name || p.model}</option>
              ))}
            </select>
          </div>
        )}

        {mode === "ai" && aiProviders.length === 0 && (
          <div style={{ background: "#f59e0b18", border: "1px solid #f59e0b40",
            borderRadius: 8, padding: "10px 14px", fontSize: 12, color: "#f59e0b" }}>
            ⚠ No LLM providers configured. Will use Claude AI directly via API.
            Configure providers in Settings for more options.
          </div>
        )}

        {/* Map stats */}
        <div style={{ display: "flex", gap: 12 }}>
          {[
            ["Nodes", nodes.length],
            ["Connections", edges.length],
            ["Notes", nodes.reduce((a, n) => a + (Array.isArray(n.notes) ? n.notes.filter(x => !x.sensitive).length : 0), 0)],
          ].map(([label, count]) => (
            <div key={label} style={{ flex: 1, background: "var(--bg3)", borderRadius: 8,
              padding: "10px 14px", textAlign: "center" }}>
              <div style={{ fontSize: 20, fontWeight: 700, color: "var(--accent)" }}>{count}</div>
              <div style={{ fontSize: 10, color: "var(--text4)" }}>{label}</div>
            </div>
          ))}
        </div>

        {/* Status */}
        {progress && (
          <div style={{ fontSize: 12, color: status === "error" ? "var(--danger)" : "var(--text3)",
            display: "flex", alignItems: "center", gap: 8 }}>
            {status === "generating" && (
              <div style={{ width: 12, height: 12, border: "2px solid var(--accent)",
                borderTopColor: "transparent", borderRadius: "50%",
                animation: "spin 0.8s linear infinite", flexShrink: 0 }}/>
            )}
            {status === "done" && <span style={{ color: "var(--success)" }}>✓</span>}
            {status === "error" && <span>✗</span>}
            {progress}
          </div>
        )}

        {/* Actions */}
        <div style={{ display: "flex", gap: 10 }}>
          <button onClick={onClose}
            style={{ padding: "10px 18px", background: "var(--bg3)", border: "1px solid var(--border)",
              borderRadius: 8, color: "var(--text3)", cursor: "pointer", fontSize: 13, fontFamily: "var(--font-ui)" }}>
            {status === "done" ? "Close" : "Cancel"}
          </button>
          <button onClick={doExport} disabled={status === "generating"}
            style={{ flex: 1, padding: "10px 18px", background: status === "generating" ? "var(--bg3)" : "var(--accent2)",
              border: "none", borderRadius: 8, color: status === "generating" ? "var(--text4)" : "#fff",
              cursor: status === "generating" ? "not-allowed" : "pointer",
              fontSize: 13, fontWeight: 700, fontFamily: "var(--font-ui)" }}>
            {status === "generating" ? "Generating…"
              : status === "done" ? "Download Again ↓"
              : `Export as Word (.docx) ↓`}
          </button>
        </div>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
