// Shared changelog — imported by NodeCanvas and Dashboard
// Pure JS array only — no JSX allowed in this .js file
export const CHANGELOG = [
  {v:"v5.36.0",date:"Apr 2026",items:[
    "Security: WebSocket JOIN now verifies map access before admitting clients to a room (was auth-only, no map permission check)",
    "Security: Version history routes (GET/POST/DELETE) now enforce mapPermission — previously any authenticated user could read or delete any map's version snapshots",
    "Security: SSRF guard added to all integration proxy routes (Proxmox, TrueNAS, Unraid, ESXi, probe) — blocks RFC-1918, loopback, link-local, and internal Docker hostnames",
    "Security: Integration proxy TLS bypass scoped to a dedicated https.Agent — no longer set globally (previously NODE_TLS_REJECT_UNAUTHORIZED=0 disabled TLS for all outbound requests including LLM APIs)",
    "Security: Gemini API key moved from URL query parameter to x-goog-api-key header — prevents key exposure in access logs",
    "Security: PATCH /users/:id self-update now respects allow_username_change and allow_avatar_change admin settings (same as /users/me)",
    "Security: Global settings PATCH now validates against an allowlist of known keys — rejects unknown keys with 400",
    "Fix: Audit log query corrected — was referencing actor_id/target_user_id columns that don't exist in schema; now uses user_id (Admin audit tab now shows actor names)",
    "Fix: Concurrent map saves no longer cause edge data loss — replaced delete-all-reinsert with upsert (INSERT … ON CONFLICT DO UPDATE) keyed by edge ID",
    "Fix: 'restricted' role added to user_role DB enum via migration — previously creating a user with this role threw a PostgreSQL constraint error",
    "Fix: Removed duplicate console.error in login error handler",
    "Fix: Server startup log now reads version from package.json instead of hardcoded v5.23.0",
    "Reliability: Expired and revoked refresh tokens are now automatically purged on startup and every 24h — prevents unbounded table growth",
    "Security: frontend nginx now serves Content-Security-Policy, X-Content-Type-Options, X-Frame-Options, and Referrer-Policy headers",
    "Security: Logs endpoint no longer leaks raw PostgreSQL error messages in API responses",
  ]},
  {v:"v5.35.5",date:"Apr 2026",items:["Dashboard map cards redesigned — now fully skin-aware via CSS class nn-map-card and --ca CSS custom property per card","Each skin has unique card personality: Neumorphic clay dual-shadow, Brutalist yellow offset box-shadow, Neon Tokyo border glow, Vapor neon haze, Newspaper editorial offset, Coral spring lift, Carbon inset highlight, Pastel Pop spring scale, Aurora glass hover glow","Actions (edit/menu) hidden by default, fade in on hover via CSS opacity transition","All hardcoded colors removed from cards: radius uses var(--radius-lg), transition uses var(--transition-all), badges use var(--ca) and theme vars","List view rows also skin-aware with per-skin hover effects","Section headers use var(--radius-btn) and var(--letter-space)"]},
  {v:"v5.35.4",date:"Apr 2026",items:["Neumorphic skin restored to v5.34.3 exact appearance — added dedicated Clay theme with --neu-dark:#bec7d8 and --neu-light:#f4faff CSS vars","Neumorphic shadows now use dual-direction technique: dark bottom-right + light top-left matching the original pressed-clay feel","Added CLAUDE.md, docs/ARCHITECTURE.md, docs/SKINS.md, docs/FEATURES.md for project handover"]},
  {v:"v5.35.3",date:"Apr 2026",items:["Live Dashboard tab now accessible in ALL skins — compact nav strip (Maps/Live/user) shows inside content area for non-sidebar skins","Each skin now has defaultAccent matching its v5.34.3 original colors applied on switch","Skin switch now applies: defaultTheme + defaultDesign + defaultAccent — full v5.34.3 restore","Accent override persists per skin in localStorage; switching skins resets to that skin's default"]},
  {v:"v5.35.2",date:"Apr 2026",items:["Architecture fix: Theme=colors, Design=spacing, Skin=personality — fully independent, any combo works","Design tab now actually works — removed font/radius/shadow from DesignContext so skins no longer override it","13 themes with completely redesigned color palettes: Dark, Midnight (Tokyo Night inspired), Forest (teal-tinted), Ocean (deep abyss), Amber (volcanic warm), Violet (Dracula purple), Light, Cream, Sepia, Rose, Soft Blue, Mint, Parchment","Each skin has: defaultTheme + defaultDesign applied on first switch, plus curated accentOptions","Accent quick-pick per skin in Skins tab — 5 curated accent colors that look great with each skin personality","Skin CSS effects (glow, scanlines, backdrop-filter) now use var(--accent) so they inherit whatever accent is active","DesignContext: 5 designs — Workspace/Clean/Comfort/Professional/Minimal — spacing/density only"]},
  {v:"v5.35.0",date:"Apr 2026",items:["Skins rewritten — NO hardcoded colors, all use CSS vars (var(--accent), var(--bg), etc.) so any theme works with any skin","Any skin+theme+design combination now works correctly","SkinContext: vars applied with setTimeout(0) deferred so they always win over theme+design; re-applied on nn-theme-changed and nn-design-changed events","Provider order fixed: Theme → Design → Skin (innermost = wins)","ThemePicker: fixed modal to 680px max-width, 680px max-height, always same size regardless of tab","ThemePicker: content area uses flex with minHeight:0 and overflowY:auto — fully scrollable","ThemePicker: tabs bar uses flexWrap so never overflows","URL fragments added: #dashboard, #live, #canvas/{mapId}, #admin — hash restored on page load","Dashboard: sidebar nav and strip-nav both update window.location.hash on tab change","All nav options (Maps/Live tabs) now available in all skins via compact strip when sidebar hidden"]},
  {v:"v5.34.3",date:"Apr 2026",items:["Fixed provider order — SkinProvider now innermost so skin vars always win over theme+design","Skin vars deferred with setTimeout(0) to guarantee they apply after theme/design effects","Skin↔Theme↔Design pairings: switching skin auto-applies recommended theme and design","Theme/design contexts fire custom events (nn-theme-changed, nn-design-changed) so SkinContext can re-apply skin vars on top","Appearance modal width increased to 720px, skin grid changed to 2-column","Skin cards now show concept description snippet"]},
  {v:"v5.34.0",date:"Apr 2026",items:["10 distinct skins, each with a unique personality and navigation layout","4 navigation layouts: Top Nav (standard), Bottom Dock (floating bar), Icon Dock (vertical 56px icons), Editorial (full-width centered)","Aurora: glassmorphism, frosted glass, animated space gradients","Brutalist: black+yellow, thick offset shadows, bottom dock, everything uppercase","Neon Tokyo: cyberpunk, CRT scanlines, hot pink+cyan glow, bottom dock","Neumorphic: soft clay 3D, dual-shadow emboss, icon dock, press-in buttons","Sakura: Japanese serif, Ma whitespace, cherry blossom, icon dock","Vapor: vaporwave 80s, grid lines, hot pink+purple+cyan, editorial full-width","Newspaper: Playfair Display serif, editorial layout, red+black+white","Coral: Miami tropical, bouncy animations, bottom dock","Carbon: carbon fiber texture, amber precision, icon dock","Pastel Pop: kawaii gradients, springy hover, giant radius, bottom dock"]},
  {v:"v5.33.2",date:"Apr 2026",items:["Skins fully rebuilt — each skin now overrides ALL color + design vars in one shot, completely replacing the previous theme","Aurora: deep space + animated radial aurora gradients, frosted glass topbar/sidebar with backdrop-filter","Brutalist: pure black + brutal yellow, 0px radius, thick borders, offset box-shadows, button press transform effects","Neon Tokyo: hot pink + cyan, CRT scanline overlay via CSS, neon glow text/borders on hover, gradient scrollbar, rainbow topbar line","Neumorphic: soft clay 3D surfaces, dual-direction box-shadows, embossed inputs, convex/concave button states","Sakura: Japanese minimal with Cormorant Garamond serif, cherry blossom palette, small-caps buttons, hairline borders","Obsidian: refined default — JetBrains Mono, GitHub-dark colors, clean scrollbars","Skin gallery: mini UI preview per card showing fake topbar + card layout in each skin","Skin picker shows active skin description at bottom"]},
  {v:"v5.33.0",date:"Apr 2026",items:["6 distinct UI skins — each with unique font, spacing, radius, shadow, and effect system","Default: JetBrains Mono, dense technical layout","Glass: frosted glassmorphism with backdrop-blur on topbar and sidebar","Terminal: green phosphor, CRT scanlines, zero border-radius, all-caps text","Cyber: Rajdhani font, neon glow, sharp angles, electric accents, neon bottom line on topbar","Paper: Lora serif, warm cream palette, physical multi-layer box shadows, press-effect buttons","Slate: Inter font, subtle neutral gray, Linear/Figma-like professional feel","Skin switcher in Appearance → ✨ Skins tab — live switch with no reload","Each skin persists to localStorage and coexists with color themes + design settings","Skins apply CSS body class for global effects (scanlines, glow, backdrop-filter, etc.)"]},
  {v:"v5.32.0",date:"Apr 2026",items:["Map cards: colored top-border accent + icon per map, node count badge in accent color, tighter layout","Grid / List view toggle — list view shows all maps in a compact table with left accent border","Map grouping: assign any map to a group (Personal, Work, Infrastructure, Network, Security, Archive, or custom) — groups render as labeled sections with divider lines","Map customization modal (✎ button): pick icon from 15 options, color from 10 accent swatches, type a custom group name or pick a preset","Search bar filters across all groups simultaneously","Group filter pills show count per group","Ungrouped maps appear first, then each group in order"]},
  {v:"v5.31.2",date:"Apr 2026",items:["Dashboard redesigned as sidebar + content layout — 220px left sidebar with user avatar/stats/nav, full remaining width for content","Sidebar shows Maps count and total node count as stat boxes","Tab switcher moved to sidebar nav with accent left-border indicator","What's new button moved to sidebar bottom","Topbar: avatar pill replaces bare circle","Content area has proper section title and full-width map grid"]},
  {v:"v5.31.1",date:"Apr 2026",items:["Topbar: avatar pill with name, tighter height, cleaner right-side actions","Dashboard: restored original header look (large title + tab switcher + version badge inline), max-width 1440px, 32px side padding","Map cards: 230px min-width, 16px padding, hover shadow, smoother transitions","Live dashboard card actions: map name vs standalone label"]},
  {v:"v5.31.0",date:"Apr 2026",items:["Fix NaN% on storage pools — handles all Proxmox storage types (ZFS, NFS, SMB/CIFS, LVM, dir) by checking used/disk_used/maxdisk fields","Deduplication: same server in multiple maps/nodes shows only once in Live Dashboard (deduped by URL)","Standalone integrations: add servers directly to Live Dashboard without creating a map node — persisted in localStorage with remove button","Dashboard layout: max-width 1400px (was 920), reduced padding, compact header bar — tabs+username in single line","Live tab hides New Map / Import buttons to reduce clutter","Map grid: 200px min-width cards"]},
  {v:"v5.30.6",date:"Apr 2026",items:["Live Dashboard: always-visible metrics strip (CPU/RAM/disk/counts) + fixed 220px scroll tab area — cards never change size","Fixed stray } rendering bug","Map cards: denser grid (200px min), compact padding","Live dashboard card: left-border color accent per integration type"]},
  {v:"v5.30.5",date:"Apr 2026",items:["Live Dashboard: fixed card height (380px) with internal scroll — adding more integrations never shifts tile sizes","All cards uniform in grid regardless of content volume"]},
  {v:"v5.30.4",date:"Apr 2026",items:[
    "Live Dashboard: replaced show/hide toggle with tabs per card — Proxmox (Overview/Guests/Storage), TrueNAS (Overview/Pools/Services), Unraid (Overview/Docker/VMs)",
    "All colors now use CSS variables matching the app theme palette",
    "Fixed guest row alignment — CPU and RAM bars in equal 2-column grid",
    "Popup width increased to 520px, maxHeight set to 80vh to prevent overflow",
  ]},
  {v:"v5.30.0",date:"Apr 2026",items:[
    "Live integrations: Proxmox VE, TrueNAS/FreeNAS, Unraid, VMware ESXi/vCenter, Generic HTTP probe — server-side proxy avoids CORS, self-signed TLS allowed",
    "📡 Live tab on nodes: configure credentials per node, connect and see live CPU/RAM/disk/VMs/containers/pool metrics with auto-refresh every 30s",
    "Proxmox: per-node CPU %, RAM %, disk %, running VMs + LXC count, VM status badges",
    "TrueNAS: hostname/version/uptime, pool health + capacity bars, running services, active alerts",
    "Unraid: CPU/RAM bars, Docker container list with running state (requires Unraid API community plugin)",
    "ESXi/vCenter: host + VM list via vSphere REST API (requires ESXi 7+ or vCenter 6.7+)",
    "HTTP probe: online/offline status + latency for any node type",
    "📡 Live Dashboard tab on homepage: aggregated cards for all nodes with integrations configured across all maps, with global refresh and online/offline summary",
    "_integration key filtered from template properties display",
    "Backend: /api/integrations/{proxmox,truenas,unraid,esxi,probe} proxy routes with 8s timeout",
  ]},
  {v:"v5.29.1",date:"Apr 2026",items:[
    "Fix: Type and Links tabs in popup caused blank/white screen — Lucide icon components were rendered as raw React children instead of via NodeIcon; React 18 throws on this",
    "Fix: same crash in the Links (conns) tab for connected node icons",
    "New popup tabs: 🔧 Services and 🔌 Ports tabs appear automatically when a node has those arrays populated",
    "Services tab in popup: full CRUD — add/edit/delete services with name, type, status (color-coded), IP, port, image/OS; ⚡ auto badge on canvas-linked entries",
    "Ports tab in popup: full CRUD — add/edit/delete ports with label, type (grouped dropdown), connected device (datalist autocomplete from canvas edges), IP/VLAN; ⚡ Auto-fill button",
  ]},
  {v:"v5.29.0",date:"Apr 2026",items:[
    "Fix: [object Object] in Properties tab — arrays (Services, Ports) are now excluded from template property inputs in both the popup and the side panel",
    "New node types: Docker Engine, Docker Container, Docker Compose, Virtual Machine (VM), LXC Container — all in correct categories with full property defaults",
    "Auto-populate Services: connecting a service-type node (Docker, VM, LXC, Container, App, API, DB, etc.) to a host node (Server, Proxmox, Unraid, ESXi, Hyper-V, NAS, TrueNAS, RPi, Desktop, Workstation, Docker Engine, K8s) instantly adds it to the host's Services panel",
    "Auto-sync: when the service node title, IP, port, image, memory or CPU changes, its entry in the host's Services panel updates automatically",
    "Auto-remove: disconnecting an edge removes the auto-populated service entry from the host",
    "Auto entries show ⚡ auto badge linked to source node name — manual entries are never touched",
    "Docker Engine node also acts as a host — connecting Docker Containers to it populates its Services panel",
    "K8s and Docker Compose nodes also act as hosts for container/service nodes",
    "Auto-populate does not push to undo/redo history — clean workflow",
  ]},
  {v:"v5.28.0",date:"Apr 2026",items:[
    "New node types: Proxmox VE, VMware ESXi, Hyper-V Host, Unraid Server, TrueNAS, FreeNAS (all with full defaults)",
    "Services/VMs/Containers panel on server, proxmox, unraid, esxi, hyperv, appserver, nas, truenas, rpi, desktop, workstation — add Docker/VM/LXC/App services with IP, port, image/OS, memory, CPU, status",
    "Status color-coding on service cards: Running=green, Stopped=red, Error=red border",
    "Ports expanded to computers: desktop (USB 3.0, HDMI, Ethernet), laptop (USB-C, Thunderbolt 4, HDMI), workstation (dual TB4, DisplayPort, dual Ethernet, Raspberry Pi (USB, HDMI)",
    "Ports expanded to L3 switch, PoE switch, core router, edge router — with interface defaults",
    "Port type dropdown extended: Network, USB, Thunderbolt, Video, Storage, Management — 20+ types in grouped optgroups",
    "Canvas auto-populate: Ports panel shows live canvas connection badges (green=assigned, orange=unassigned)",
    "⚡ Auto-fill button: assigns unassigned edge-connected nodes to empty port slots",
    "Port row border turns green when connected device is filled; datalist autocomplete from canvas edges",
  ]},
  {v:"v5.27.3",date:"Apr 2026",items:["Critical fix: DP (default node properties map) was accidentally stripped during v5.27.0 icon refactor — caused ReferenceError on map load, resulting in empty canvas for all existing maps"]},
  {v:"v5.27.2",date:"Apr 2026",items:["Build fix: missing closing } after &&<>…</> fragment in PropsPanel TEMPLATE PROPERTIES block"]},
  {v:"v5.27.1",date:"Apr 2026",items:["Build fix: comprehensive scan and repair of all JSX expression blocks missing closing } — properties/customProps indicators, Tutorial, HelpGuide, modals, ArrowHeads, fragment blocks"]},
  {v:"v5.27.1",date:"Apr 2026",items:["Build fix: restored 10 missing closing braces stripped by overly broad />} replacement across NodeCanvas JSX expression blocks"]},
  {v:"v5.27.1",date:"Apr 2026",items:["Build fix: restored missing } after double-edge fragment close — broken by overly broad />} replacement"]},
  {v:"v5.27.1",date:"Apr 2026",items:["Build fix: removed bad />} regex replacement that broke JSX expression blocks in edge renderer"]},
  {v:"v5.27.0",date:"Apr 2026",items:[
    "All 107 node icons replaced with clean Lucide SVG icons — crisp at any size, theme-aware, no emoji rendering inconsistencies",
    "Added lucide-react library — consistent stroke-based icon design across all nodes",
    "NodeIcon component: renders Lucide SVG in UI, graceful text fallback in canvas/export contexts",
    "Every icon meaningfully chosen: FileText(note), Brain(concept), Scale(loadbalancer), TestTube(honeypot), ScanSearch(SIEM), etc.",
  ]},
  {v:"v5.26.1",date:"Apr 2026",items:[
    "All 107 node types audited and reorganized: cleaner labels, better category groupings",
    "Fixed 18 duplicate icons — every node now has a unique icon for instant visual recognition",
    "Network category reorganized into logical sub-groups: Core Devices, VPN & WAN, Routing Tiers, Infrastructure Services",
    "New unique icons: heading→🔡, blocker→🛑, reference→📑, esp→📻, sensor→🌡️, tablet→🗒️, gateway→🚪, nas→🗂️, backup→♻️, ids→🚨, siem→🔭, apigateway→🚦, cache→💨, software→💽, database→🏦, api→🔗 and more",
  ]},
  {v:"v5.26.0",date:"Apr 2026",items:[
    "Network nodes: 18 new types — VPN Client/Server/Concentrator, SD-WAN, Core/Edge Router, L3/PoE Switch, Wireless Controller, DHCP/DNS/NTP/RADIUS servers, Patch Panel, Network TAP, Monitor, Honeypot",
    "Notes category: 11 new note-taking nodes — Idea, Topic, Concept, Definition, Quote, Summary, Question, Answer, Warning, Tip, Code Block",
    "Planning category: 9 new nodes — Task, Checklist, Goal, Milestone, Deadline, Blocker, Step, Problem, Solution",
    "Knowledge category: 6 new nodes — Reference, Resource, Evidence, Flashcard, Bookmark, Formula",
    "New edge types (Semantic section): Causes, Supports, Contradicts, Part of, See also, Leads to, Depends on — with semantic default colors",
    "Sidebar: Notes, Planning, Knowledge categories now appear first for note-taking workflow",
  ]},
  {v:"v5.24.16",date:"Apr 2026",items:[
    "Import fix: sanitizeImport now generates fresh crypto.randomUUID() for every node and edge — prevents ON CONFLICT silent update of source map nodes",
    "Edge from/to references remapped correctly to new node IDs after ID reassignment",
  ]},
  {v:"v5.24.15",date:"Apr 2026",items:[
    "Import fix: edge IDs now always get fresh UUIDs in save route — prevents duplicate key constraint on map_edges_pkey",
  ]},
  {v:"v5.24.14",date:"Apr 2026",items:[
    "Import: sanitizeImport normalises all node/edge fields before save (handles node_type vs type, from_node vs from)",
    "Import: orphaned empty map deleted if saveMap fails after createMap",
    "Import conflict: inline modal replaces window.confirm (Overwrite / Save as copy / Cancel)",
    "Create map duplicate: auto-renames with date suffix, no blocking dialog",
  ]},
  {v:"v5.24.13",date:"Apr 2026",items:[
    "Import: all alert() calls replaced with toast notifications",
    "Import: auto-navigates into map after successful import (no more click-the-card)",
    "Save guard: skips DB save when both nodes and edges are empty (prevents spurious save-failed on blank maps)",
  ]},
  {v:"v5.24.12",date:"Apr 2026",items:[
    "Dashboard: createWithUnique was undefined — replaced with inline duplicate-name handling",
  ]},
  {v:"v5.24.11",date:"Apr 2026",items:[
    "Backend maps.js: missing imports restored (authenticate, mapPermission, query, withTransaction, body, validationResult)",
  ]},
  {v:"v5.24.10",date:"Apr 2026",items:[
    "Duplicate map: now generates fresh UUIDs for all nodes and edges — prevents primary key conflicts on repeated duplication",
    "Duplicate map: edge node references remapped to new node IDs",
    "Duplicate map: from_anchor, to_anchor, mid_off now copied correctly",
  ]},
  {v:"v5.24.9",date:"Apr 2026",items:[
    "Notes corruption root cause: literal newline character in content caused JSON.parse to throw Bad control character — fixed by escaping control chars before re-parsing",
    "Fix applied in three places: backend normalizeNotes (GET response), backend fixCorruptedNotes (DB migration), frontend tryExtractNotes",
  ]},
  {v:"v5.24.8",date:"Apr 2026",items:[
    "Notes corruption: fixed at DB level — backend migration repairs all corrupted notes on startup",
    "GET /maps/:id now normalizes notes before sending, so corruption can never reach the frontend",
  ]},
  {v:"v5.24.7",date:"Apr 2026",items:["Notes corruption fix: handles all patterns including missing-bracket JSON fragments like {id:...},{id:...}",
    "Changelog deduplication: version entries no longer stack on each update",]},
  {v:"v5.24.6",date:"Apr 2026",items:["Notes: corrupted notes (notes-JSON stored as note content) unwrapped into individual notes",]},
  {v:"v5.24.5",date:"Apr 2026",items:["Custom property key duplicate: red border + error message shown live while typing",
    "Custom key input: reverts on blur if name is duplicate or empty",]},
  {v:"v5.24.4",date:"Apr 2026",items:["Custom property key editable: switched from controlled to uncontrolled input (defaultValue+key) so typing works",]},
  {v:"v5.24.3",date:"Apr 2026",items:["Existing nodes now get new default properties on load (DP defaults merged, existing values preserved)",
    "Custom properties: key name editable in both PropsPanel and inline editor — blur to rename",
    "Custom property key uniqueness enforced across default and custom fields",
    "N shortcut: fixed — selected node gets inline note first; bare N adds a note-type node",]},
  {v:"v5.24.2",date:"Apr 2026",items:["Switch node: IP field confirmed present (also added IP to NAS, storage, SAN, IoT, sensors, industrial nodes)",
    "Custom properties: key/name is now editable — click and type a new name, blur to rename (unique per node)",
    "Custom property key uniqueness enforced against both default and custom property names",
    "N shortcut: fixed execution order — selected node gets inline note, bare N adds a note-type node",]},
  {v:"v5.24.1",date:"Apr 2026",items:["IP field added to all network devices: VPN, AP, modem, WAN link, laptop, workstation, thin client, app/DB/file/mail servers, NAS, mobile, tablet, IoT (RPi, ESP), gateway, IDS, WAF, cache, broker, microservice, API, k8s",
    "Note add (+ button or N shortcut) now opens inline in edit mode with title auto-focused — no popup",
    "Keyboard N shortcut: adds inline note to selected node (same as clicking + note, works in edit mode)",
    "Delete button (✕) added beside each note's edit pencil — hover the note row to see both icons",]},
  {v:"v5.24.0",date:"Apr 2026",items:["Dashboard: Import .nonote — fixed auth, saves before navigating, no longer opens empty canvas",
    "Dashboard: Share map opens inline modal — no longer navigates away to map view",
    "Map title uniqueness: conflict dialog with Rename or Overwrite options on create and import",
    "Dashboard: Export .nonote and Duplicate fixed (apiFetch double-parse bug)",
    "Logout button added to canvas topbar and renamed from \u2192 OUT in dashboard header",]},
  {v:"v5.23.2",date:"Apr 2026",items:["Canvas theme now actually applies: inline background overrides CSS vars when canvas theme differs from global",
    "ThemePicker: backdrop click-to-close fixed (target check); theme cards get stopPropagation",]},
  {v:"v5.23.1",date:"Apr 2026",items:["ThemePicker: ThemeGrid moved to module scope — was redefined each render causing click events to break",
    "ThemePicker: backdrop onClick fixed to only close on direct click, not bubbled child events",]},
  {v:"v5.23.0",date:"Apr 2026",items:["Node IP/Domain/Subnet/MAC fields on all network/server/device nodes",
    "Router & Switch port tables: configurable per-interface name, type, connected device, IP/VLAN",
    "Inline new note creation on nodes — no popup required",
    "ThemePicker: fixed z-index so theme selection works from canvas",
    "Tutorial spotlight: proper darkening — target element stays fully visible",
    "Admin logs now populated: login, user create/delete, map create events",
    "Versioning: semantic versioning (major.minor.patch) from this version onwards",]},
  {v:"v5.22",date:"Apr 2026",items:["Browser back button now navigates within app (History API pushState)",
    "Changelog shared across Dashboard and canvas — single source of truth",
    "Word (.docx) export: Normal mode — structured docs from nodes/notes/connections",
    "AI Word Doc export: LLM interprets your map into professional prose documentation",
    "Mobile: arrow/edge rendering fixed (explicit SVG dimensions)",
    "Mobile: full feature parity — connect mode, add nodes, notes, drag, collab",]},
  {v:"v5.21",date:"Apr 2026",items:["Arrow routing: smarter bestSides scoring eliminates wrong-face exits",
    "Bezier curves: adaptive handle length reduces path crossings",
    "Expand All now runs auto-layout to prevent node overlaps",
    "Space bar quick capture: offsets each new node to avoid stacking",
    "Topbar Row 1: icon-only buttons with hover tooltips, cleaner grouping",
    "Topbar reorganized: Row 1 = app actions, Row 2 = canvas tools",]},
  {v:"v5.20",date:"Apr 2026",items:["Tutorial mode: interactive step-by-step walkthrough with spotlight on UI elements",
    "Help Guide: full searchable documentation with 10 sections and keyboard shortcut table",
    "Tutorial and Help accessible from canvas topbar (🎓 and ? buttons) and dashboard header",
    "Tutorial adapts to current page — shows dashboard or canvas steps accordingly",
    "Focus mode now dims edges (v5.19 fix carried over)",
    "Drag select fixed: didBoxSel ref prevents onClick from clearing box-selection",]},
  {v:"v5.19",date:"Apr 2026",items:["Focus mode now dims edges too (not just nodes)",
    "Drag select fixed: canvas onClick was clearing box-selection immediately after commit",]},
  {v:"v5.18",date:"Apr 2026",items:["Collab: Excel-style selection overlays — selected nodes get colored border + name badge",
    "Collab: editing state shows '· editing' in the badge (like Google Docs)",
    "Collab: stacked avatar pill in topbar with green dot = user is actively selecting",
    "Collab: removed cursor tracking — only selection state is broadcast",
    "Collab: corner handle dot on selected node (Excel fill handle style)",]},
  {v:"v5.17",date:"Apr 2026",items:["Collab FIXED: broadcast moved to scheduleSave — covers ALL 15 state-update paths",
    "Drag/resize/notes/all mutations now broadcast (previously only applyNodes did)",
    "150ms debounce on WS broadcast batches rapid drag pixels into one message",
    "No side effects inside React state updaters — applyNodes/applyEdges are clean",
    "Echo prevention: server never sends back to the sender (server-side, reliable)",]},
  {v:"v5.16",date:"Apr 2026",items:["Collab rebuilt: applyNodes/applyEdges broadcast ws.send() directly on local change",
    "Collab: receiver calls setNodes/setEdges directly — never applyNodes (no echo possible)",
    "Collab: no useEffect broadcasting — React batch timing issues eliminated entirely",
    "Collab: always-on WS, auto-reconnects on disconnect, no toggle button",
    "MS Office cursors: colored arrow + name badge per collaborator",]},
  {v:"v5.15",date:"Apr 2026",items:["Collaboration is now always-on — auto-connects when any map is open (no toggle button)",
    "MS Office-style cursor presence: colored cursor arrow + name badge per user",
    "Live presence pill in topbar shows avatars + count when others are viewing",
    "Deterministic per-user color (consistent across sessions)",
    "Backend crash fix: runMigrations function was missing (was causing restarting loop)",
    "Login fix: /auth/me and /auth/logout now correctly send access token",]},
  {v:"v5.14",date:"Apr 2026",items:["Login fix: apiFetch skips stale token and 401-retry for /auth/* endpoints",
    "Refresh fix: access token stored in sessionStorage — survives page reload",
    "Perf: mousemove handler now stable (deps [zoom] only) — no re-create on every drag pixel",
    "Perf: draggingRef/resizingRef mirror state — handler reads refs, not captured state",
    "Drag select fixed: onUp handler restructured with correct separate blocks",]},
  {v:"v5.13",date:"Apr 2026",items:["Logout on refresh fixed: access token stored in sessionStorage (survives refresh)",
    "Drag select fixed: onUp handler restructured — box-select, group-box, GB drag all separate",
    "Collab rewritten: clean WS model, JSON echo prevention, 20fps cursor throttle",
    "Collab: wsConnected state (not ref) — effects fire after async connect completes",
    "Collab: auth_error message from server turns off collab gracefully",
    "Collab: auto-reconnect on unexpected close, disabled on intentional close",
    "Backend WS: simple broadcast function, no Redis, correct JWT_ACCESS_SECRET",]},
  {v:"v5.12",date:"Apr 2026",items:["Collab: JWT_ACCESS_SECRET fix — WS auth now works (was using wrong env var)",
    "Collab: Redis pub/sub backend — messages fan-out via Redis, works across instances",
    "Collab: wsConnected state (not just ref) — broadcast effects fire after async connect",
    "Collab: server-side echo filter — subscriber skips sending back to the publisher",
    "Collab: 🟡 connecting → 🟢 live indicator driven by room_state acknowledgement",
    "Auto-migrations: backend runs migrate.sql on every startup (safe IF NOT EXISTS)",
    "migrate.sql: all manual ALTER TABLE / CREATE TABLE in one idempotent file",]},
  {v:"v5.11",date:"Apr 2026",items:["Collab WS: echo prevention fixed using object identity (nodes===lastRemoteNodes.current)",
    "Collab WS: backend now fetches display_name, broadcasts room_state + user_joined events",
    "Collab WS: auto-reconnect on unexpected disconnect (3s delay)",
    "Remote cursors: colored dots with name tags show each user's position live",
    "Changes panel (📋): floating panel showing who changed what with timestamps",
    "Backend logs add/delete/edit_node and add/delete_edge to map_changelog table",
    "WS server broadcasts userId+userName so all receiving clients know who made changes",]},
  {v:"v5.10",date:"Apr 2026",items:["Real-time collaboration: changes now broadcast immediately via applyNodes/applyEdges hooks",
    "WS auth fixed: uses getAccessToken() getter instead of missing localStorage key",
    "Shared map indicator in topbar: collaborators see '👁 Shared · viewer/editor by Owner'",
    "Owner indicator: owners with active shares see '👥 Shared · N people'",
    "Dashboard: map cards show shared-to-me badge (with owner name) and shared-by-me badge",
    "Backend: maps list now returns owner_id and collab_count for badge logic",]},
  {v:"v5.9",date:"Apr 2026",items:["Share map fixed: all API calls now use apiFetch with proper auth token (not localStorage)",
    "Topbar reorganized into 4 logical groups: Map Resources | Import+Export | Collaboration | Appearance+View",
    "Share button no longer overlaps Export — each has its own group with separators",
    "Dashboard fetch calls (rename, duplicate, export) also fixed to use apiFetch",]},
  {v:"v5.8",date:"Apr 2026",items:["Group boxes: drag to move, SE corner resize, border color picker, fill color picker",
    "PDF export: print-dialog PDF with embedded node structure (🖨 Print / Save as PDF)",
    "Group boxes persisted to DB (group_boxes JSONB column in maps table)",
    "nginx WebSocket proxy added (/ws location) — real-time collaboration now fully routable",
    "Keyboard shortcut G added to tooltip reference",]},
  {v:"v5.7",date:"Apr 2026",items:["Arrow crossing minimization: port t-values sorted by target position, no crossing between parallel edges",
    "Map title inline editable in topbar (click to rename)",
    "Box select: live node count shown inside selection rect, works in view mode",
    "All dropdowns open below their button (not fixed top-right corner)",
    "Share modal: user search autocomplete as you type, better error messages",
    "Group box drawing (G key): label, solid/dashed/dotted, click × to delete",
    "Export: HTML (view-only interactive page) and Markdown documentation",
    "Dashboard: Share option in map context menu",]},
  {v:"v5.6",date:"Apr 2026",items:["Build fix: JSX fragment wrapper for Collab button inside canEdit&&()",
    "Dashboard: Import .nonote opens map directly (no empty map created first)",
    "Dashboard: Map cards have ⋮ context menu — Open, Rename, Duplicate, Export, Delete",
    "Dashboard: right-click map card also opens context menu",
    "Backend: PATCH /maps/:id for rename, POST /maps/:id/duplicate",
    "Backend: GET /maps/:id/collaborators endpoint added",]},
  {v:"v5.5",date:"Apr 2026",items:["Share map: 👥 button to invite collaborators with Viewer/Editor roles",
    "Real-time collaboration: WebSocket sync — 🟢 Collab toggle broadcasts changes live",
    "Inline formatting toolbar on note edit: Bold, Italic, Underline, Strikethrough, HR",
    "Changelog now shown on home page (Dashboard)",
    "Arrow markerEnd arrowhead flush fix — removed incorrect endpoint nudge",]},
  {v:"v5.4",date:"Apr 2026",items:["Arrow tip flush fix: endpoint nudged INTO node so arrowhead is visually flush",
    "Description placeholder no longer shown twice (removed duplicate from node body)",
    "Icon grid uses CSS auto-fill — no more trailing empty gap in last row",]},
  {v:"v5.3",date:"Apr 2026",items:["Compact sidebar redesigned: narrower 136px panel, categories preserved, search works in all modes",
    "Arrow gap fix: markerEnd nudged slightly inward so arrowhead is flush with node edge",
    "Arrow bidirectional start correctly pulled forward by markerWidth×strokeWidth",
    "Icon sidebar tooltip shown in compact mode too",]},
  {v:"v5.2",date:"Apr 2026",items:["Arrow endpoint pull fixed: markerEnd no longer creates gap, markerStart correctly offset",
    "Compact sidebar mode now works — fixed out-of-scope state call bug",
    "Node library title no longer truncates in compact/icon modes",
    "Note content inline editable directly on canvas — click ✎ to edit",
    "Bidirectional arrow endpoints now correctly clear both node borders",
    "Node header redesigned: title + description in header, type label at right-bottom",
    "Comment 💬 and Collapse ⊟ icons share one row, no overlap",
    "Pencil ✎ icons on title, description, note title, and note content",
    "Inline note title editing without opening popup",
    "Changelog now maintained automatically in every version",]},
  {v:"v5.0",date:"Apr 2026",items:["Bidirectional arrows correctly show both arrowheads (auto-start-reverse)",
    "Inline text editing: pencil icon on title and description (F2 to rename)",
    "Keyboard shortcuts: E opens node popup, N adds note, F2 renames",
    "Compact sidebar mode: multi-icon dense grid",
    "Node type badge moved to right-bottom, less distracting",
    "Node description displayed directly under title",
    "Export/Import .nonote bundle format",
    "Focus mode activates on node click",
    "Resize snap guides",
    "Notes on node: expand per title, expand all button",
    "Quick add note button on node hover",]},
  {v:"v4.46–4.47",date:"2026",items:["Recursive subtree auto-layout (no overlapping nodes)",
    "5 layout directions: L→R, T→B, R→L, B→T, Radial",
    "Layout direction picker dropdown",
    "Popup closes on canvas click",
    "Absolute layer positions eliminate X-axis overlap",]},
  {v:"v4.42–4.45",date:"2026",items:["Complete search rewrite — searches all node data including note titles",
    "Edge routing: smart right→left preference for horizontal layouts",
    "Endpoint drag: slide t-offset along side, reset button",
    "Left-to-right tree layout",]},
  {v:"v4.38–4.41",date:"2026",items:["Canvas area restored + renderEdges/renderNodes helpers",
    "Node Library: collapse, icon-only, dense modes",
    "5-direction auto layout (LR/TB/RL/BT/Radial)",
    "Smart edge router with bestSides()",
    "Improved search covering note titles and descriptions",]},
  {v:"v4.33–4.37",date:"2026",items:["Multi-note per node (array of notes)",
    "Rich text editor with formatting toolbar",
    "Sensitive data toggle on notes (redacted in LLM export)",
    "Inline node editor popup on double-click (4 tabs)",
    "Node type picker in popup",
    "POPUP / PANEL toggle for properties mode",
    "Redesigned 2-row topbar with functional grouping",
    "Command-palette search overlay",]},
  {v:"v4.25–4.32",date:"2026",items:["Right-click context menu",
    "Snap-to-grid (Shift+drag)",
    "Alignment guides during drag",
    "Status dots on collapsed nodes",
    "Template library (Homelab, Microservices, Mind Map)",
    "Comment pins with threaded sidebar",
    "15 connection styles",
    "Focus mode (dims non-active nodes)",
    "Quick capture (Space bar)",
    "Ctrl+D duplicate",]},
  {v:"v4.0–4.24",date:"2025–2026",items:["Full-stack app: Node.js + PostgreSQL + Redis + Docker",
    "60+ node types across 9 categories",
    "Collision prevention with AABB detection",
    "Anchor system for connection endpoints",
    "Version history with restore",
    "LLM export and AI Chat panel",
    "Custom node properties and themes",
    "PNG export",]},
];


// Single source of truth for current version — always the first entry in CHANGELOG
export const CURRENT_VERSION = CHANGELOG[0].v;
