// Shared changelog — imported by NodeCanvas and Dashboard
// Pure JS array only — no JSX allowed in this .js file
export const CHANGELOG = [
  {v:"v5.24.16",date:"Apr 2026",items:[
    "Import fix: sanitizeImport now generates fresh crypto.randomUUID() for every node and edge — prevents ON CONFLICT silent update of source map nodes",
    "Edge from/to references remapped correctly to new node IDs after ID reassignment",
  ]},
  {v:"v5.24.15",date:"Apr 2026",items:[
    "Import fix: edge IDs now always get fresh UUIDs in save route — prevents duplicate key constraint on map_edges_pkey",
  ]},
  {v:"v5.24.14",date:"Apr 2026",items:[
    "Import: sanitizeImport normalises all node/edge fields before save (handles node_type vs type, from_node vs from)",
    "Import: orphaned empty map deleted if saveMap fails after createMap",
    "Import conflict: inline modal replaces window.confirm (Overwrite / Save as copy / Cancel)",
    "Create map duplicate: auto-renames with date suffix, no blocking dialog",
  ]},
  {v:"v5.24.13",date:"Apr 2026",items:[
    "Import: all alert() calls replaced with toast notifications",
    "Import: auto-navigates into map after successful import (no more click-the-card)",
    "Save guard: skips DB save when both nodes and edges are empty (prevents spurious save-failed on blank maps)",
  ]},
  {v:"v5.24.12",date:"Apr 2026",items:[
    "Dashboard: createWithUnique was undefined — replaced with inline duplicate-name handling",
  ]},
  {v:"v5.24.11",date:"Apr 2026",items:[
    "Backend maps.js: missing imports restored (authenticate, mapPermission, query, withTransaction, body, validationResult)",
  ]},
  {v:"v5.24.10",date:"Apr 2026",items:[
    "Duplicate map: now generates fresh UUIDs for all nodes and edges — prevents primary key conflicts on repeated duplication",
    "Duplicate map: edge node references remapped to new node IDs",
    "Duplicate map: from_anchor, to_anchor, mid_off now copied correctly",
  ]},
  {v:"v5.24.9",date:"Apr 2026",items:[
    "Notes corruption root cause: literal newline character in content caused JSON.parse to throw Bad control character — fixed by escaping control chars before re-parsing",
    "Fix applied in three places: backend normalizeNotes (GET response), backend fixCorruptedNotes (DB migration), frontend tryExtractNotes",
  ]},
  {v:"v5.24.8",date:"Apr 2026",items:[
    "Notes corruption: fixed at DB level — backend migration repairs all corrupted notes on startup",
    "GET /maps/:id now normalizes notes before sending, so corruption can never reach the frontend",
  ]},
  {v:"v5.24.7",date:"Apr 2026",items:["Notes corruption fix: handles all patterns including missing-bracket JSON fragments like {id:...},{id:...}",
    "Changelog deduplication: version entries no longer stack on each update",]},
  {v:"v5.24.6",date:"Apr 2026",items:["Notes: corrupted notes (notes-JSON stored as note content) unwrapped into individual notes",]},
  {v:"v5.24.5",date:"Apr 2026",items:["Custom property key duplicate: red border + error message shown live while typing",
    "Custom key input: reverts on blur if name is duplicate or empty",]},
  {v:"v5.24.4",date:"Apr 2026",items:["Custom property key editable: switched from controlled to uncontrolled input (defaultValue+key) so typing works",]},
  {v:"v5.24.3",date:"Apr 2026",items:["Existing nodes now get new default properties on load (DP defaults merged, existing values preserved)",
    "Custom properties: key name editable in both PropsPanel and inline editor — blur to rename",
    "Custom property key uniqueness enforced across default and custom fields",
    "N shortcut: fixed — selected node gets inline note first; bare N adds a note-type node",]},
  {v:"v5.24.2",date:"Apr 2026",items:["Switch node: IP field confirmed present (also added IP to NAS, storage, SAN, IoT, sensors, industrial nodes)",
    "Custom properties: key/name is now editable — click and type a new name, blur to rename (unique per node)",
    "Custom property key uniqueness enforced against both default and custom property names",
    "N shortcut: fixed execution order — selected node gets inline note, bare N adds a note-type node",]},
  {v:"v5.24.1",date:"Apr 2026",items:["IP field added to all network devices: VPN, AP, modem, WAN link, laptop, workstation, thin client, app/DB/file/mail servers, NAS, mobile, tablet, IoT (RPi, ESP), gateway, IDS, WAF, cache, broker, microservice, API, k8s",
    "Note add (+ button or N shortcut) now opens inline in edit mode with title auto-focused — no popup",
    "Keyboard N shortcut: adds inline note to selected node (same as clicking + note, works in edit mode)",
    "Delete button (✕) added beside each note's edit pencil — hover the note row to see both icons",]},
  {v:"v5.24.0",date:"Apr 2026",items:["Dashboard: Import .nonote — fixed auth, saves before navigating, no longer opens empty canvas",
    "Dashboard: Share map opens inline modal — no longer navigates away to map view",
    "Map title uniqueness: conflict dialog with Rename or Overwrite options on create and import",
    "Dashboard: Export .nonote and Duplicate fixed (apiFetch double-parse bug)",
    "Logout button added to canvas topbar and renamed from \u2192 OUT in dashboard header",]},
  {v:"v5.23.2",date:"Apr 2026",items:["Canvas theme now actually applies: inline background overrides CSS vars when canvas theme differs from global",
    "ThemePicker: backdrop click-to-close fixed (target check); theme cards get stopPropagation",]},
  {v:"v5.23.1",date:"Apr 2026",items:["ThemePicker: ThemeGrid moved to module scope — was redefined each render causing click events to break",
    "ThemePicker: backdrop onClick fixed to only close on direct click, not bubbled child events",]},
  {v:"v5.23.0",date:"Apr 2026",items:["Node IP/Domain/Subnet/MAC fields on all network/server/device nodes",
    "Router & Switch port tables: configurable per-interface name, type, connected device, IP/VLAN",
    "Inline new note creation on nodes — no popup required",
    "ThemePicker: fixed z-index so theme selection works from canvas",
    "Tutorial spotlight: proper darkening — target element stays fully visible",
    "Admin logs now populated: login, user create/delete, map create events",
    "Versioning: semantic versioning (major.minor.patch) from this version onwards",]},
  {v:"v5.22",date:"Apr 2026",items:["Browser back button now navigates within app (History API pushState)",
    "Changelog shared across Dashboard and canvas — single source of truth",
    "Word (.docx) export: Normal mode — structured docs from nodes/notes/connections",
    "AI Word Doc export: LLM interprets your map into professional prose documentation",
    "Mobile: arrow/edge rendering fixed (explicit SVG dimensions)",
    "Mobile: full feature parity — connect mode, add nodes, notes, drag, collab",]},
  {v:"v5.21",date:"Apr 2026",items:["Arrow routing: smarter bestSides scoring eliminates wrong-face exits",
    "Bezier curves: adaptive handle length reduces path crossings",
    "Expand All now runs auto-layout to prevent node overlaps",
    "Space bar quick capture: offsets each new node to avoid stacking",
    "Topbar Row 1: icon-only buttons with hover tooltips, cleaner grouping",
    "Topbar reorganized: Row 1 = app actions, Row 2 = canvas tools",]},
  {v:"v5.20",date:"Apr 2026",items:["Tutorial mode: interactive step-by-step walkthrough with spotlight on UI elements",
    "Help Guide: full searchable documentation with 10 sections and keyboard shortcut table",
    "Tutorial and Help accessible from canvas topbar (🎓 and ? buttons) and dashboard header",
    "Tutorial adapts to current page — shows dashboard or canvas steps accordingly",
    "Focus mode now dims edges (v5.19 fix carried over)",
    "Drag select fixed: didBoxSel ref prevents onClick from clearing box-selection",]},
  {v:"v5.19",date:"Apr 2026",items:["Focus mode now dims edges too (not just nodes)",
    "Drag select fixed: canvas onClick was clearing box-selection immediately after commit",]},
  {v:"v5.18",date:"Apr 2026",items:["Collab: Excel-style selection overlays — selected nodes get colored border + name badge",
    "Collab: editing state shows '· editing' in the badge (like Google Docs)",
    "Collab: stacked avatar pill in topbar with green dot = user is actively selecting",
    "Collab: removed cursor tracking — only selection state is broadcast",
    "Collab: corner handle dot on selected node (Excel fill handle style)",]},
  {v:"v5.17",date:"Apr 2026",items:["Collab FIXED: broadcast moved to scheduleSave — covers ALL 15 state-update paths",
    "Drag/resize/notes/all mutations now broadcast (previously only applyNodes did)",
    "150ms debounce on WS broadcast batches rapid drag pixels into one message",
    "No side effects inside React state updaters — applyNodes/applyEdges are clean",
    "Echo prevention: server never sends back to the sender (server-side, reliable)",]},
  {v:"v5.16",date:"Apr 2026",items:["Collab rebuilt: applyNodes/applyEdges broadcast ws.send() directly on local change",
    "Collab: receiver calls setNodes/setEdges directly — never applyNodes (no echo possible)",
    "Collab: no useEffect broadcasting — React batch timing issues eliminated entirely",
    "Collab: always-on WS, auto-reconnects on disconnect, no toggle button",
    "MS Office cursors: colored arrow + name badge per collaborator",]},
  {v:"v5.15",date:"Apr 2026",items:["Collaboration is now always-on — auto-connects when any map is open (no toggle button)",
    "MS Office-style cursor presence: colored cursor arrow + name badge per user",
    "Live presence pill in topbar shows avatars + count when others are viewing",
    "Deterministic per-user color (consistent across sessions)",
    "Backend crash fix: runMigrations function was missing (was causing restarting loop)",
    "Login fix: /auth/me and /auth/logout now correctly send access token",]},
  {v:"v5.14",date:"Apr 2026",items:["Login fix: apiFetch skips stale token and 401-retry for /auth/* endpoints",
    "Refresh fix: access token stored in sessionStorage — survives page reload",
    "Perf: mousemove handler now stable (deps [zoom] only) — no re-create on every drag pixel",
    "Perf: draggingRef/resizingRef mirror state — handler reads refs, not captured state",
    "Drag select fixed: onUp handler restructured with correct separate blocks",]},
  {v:"v5.13",date:"Apr 2026",items:["Logout on refresh fixed: access token stored in sessionStorage (survives refresh)",
    "Drag select fixed: onUp handler restructured — box-select, group-box, GB drag all separate",
    "Collab rewritten: clean WS model, JSON echo prevention, 20fps cursor throttle",
    "Collab: wsConnected state (not ref) — effects fire after async connect completes",
    "Collab: auth_error message from server turns off collab gracefully",
    "Collab: auto-reconnect on unexpected close, disabled on intentional close",
    "Backend WS: simple broadcast function, no Redis, correct JWT_ACCESS_SECRET",]},
  {v:"v5.12",date:"Apr 2026",items:["Collab: JWT_ACCESS_SECRET fix — WS auth now works (was using wrong env var)",
    "Collab: Redis pub/sub backend — messages fan-out via Redis, works across instances",
    "Collab: wsConnected state (not just ref) — broadcast effects fire after async connect",
    "Collab: server-side echo filter — subscriber skips sending back to the publisher",
    "Collab: 🟡 connecting → 🟢 live indicator driven by room_state acknowledgement",
    "Auto-migrations: backend runs migrate.sql on every startup (safe IF NOT EXISTS)",
    "migrate.sql: all manual ALTER TABLE / CREATE TABLE in one idempotent file",]},
  {v:"v5.11",date:"Apr 2026",items:["Collab WS: echo prevention fixed using object identity (nodes===lastRemoteNodes.current)",
    "Collab WS: backend now fetches display_name, broadcasts room_state + user_joined events",
    "Collab WS: auto-reconnect on unexpected disconnect (3s delay)",
    "Remote cursors: colored dots with name tags show each user's position live",
    "Changes panel (📋): floating panel showing who changed what with timestamps",
    "Backend logs add/delete/edit_node and add/delete_edge to map_changelog table",
    "WS server broadcasts userId+userName so all receiving clients know who made changes",]},
  {v:"v5.10",date:"Apr 2026",items:["Real-time collaboration: changes now broadcast immediately via applyNodes/applyEdges hooks",
    "WS auth fixed: uses getAccessToken() getter instead of missing localStorage key",
    "Shared map indicator in topbar: collaborators see '👁 Shared · viewer/editor by Owner'",
    "Owner indicator: owners with active shares see '👥 Shared · N people'",
    "Dashboard: map cards show shared-to-me badge (with owner name) and shared-by-me badge",
    "Backend: maps list now returns owner_id and collab_count for badge logic",]},
  {v:"v5.9",date:"Apr 2026",items:["Share map fixed: all API calls now use apiFetch with proper auth token (not localStorage)",
    "Topbar reorganized into 4 logical groups: Map Resources | Import+Export | Collaboration | Appearance+View",
    "Share button no longer overlaps Export — each has its own group with separators",
    "Dashboard fetch calls (rename, duplicate, export) also fixed to use apiFetch",]},
  {v:"v5.8",date:"Apr 2026",items:["Group boxes: drag to move, SE corner resize, border color picker, fill color picker",
    "PDF export: print-dialog PDF with embedded node structure (🖨 Print / Save as PDF)",
    "Group boxes persisted to DB (group_boxes JSONB column in maps table)",
    "nginx WebSocket proxy added (/ws location) — real-time collaboration now fully routable",
    "Keyboard shortcut G added to tooltip reference",]},
  {v:"v5.7",date:"Apr 2026",items:["Arrow crossing minimization: port t-values sorted by target position, no crossing between parallel edges",
    "Map title inline editable in topbar (click to rename)",
    "Box select: live node count shown inside selection rect, works in view mode",
    "All dropdowns open below their button (not fixed top-right corner)",
    "Share modal: user search autocomplete as you type, better error messages",
    "Group box drawing (G key): label, solid/dashed/dotted, click × to delete",
    "Export: HTML (view-only interactive page) and Markdown documentation",
    "Dashboard: Share option in map context menu",]},
  {v:"v5.6",date:"Apr 2026",items:["Build fix: JSX fragment wrapper for Collab button inside canEdit&&()",
    "Dashboard: Import .nonote opens map directly (no empty map created first)",
    "Dashboard: Map cards have ⋮ context menu — Open, Rename, Duplicate, Export, Delete",
    "Dashboard: right-click map card also opens context menu",
    "Backend: PATCH /maps/:id for rename, POST /maps/:id/duplicate",
    "Backend: GET /maps/:id/collaborators endpoint added",]},
  {v:"v5.5",date:"Apr 2026",items:["Share map: 👥 button to invite collaborators with Viewer/Editor roles",
    "Real-time collaboration: WebSocket sync — 🟢 Collab toggle broadcasts changes live",
    "Inline formatting toolbar on note edit: Bold, Italic, Underline, Strikethrough, HR",
    "Changelog now shown on home page (Dashboard)",
    "Arrow markerEnd arrowhead flush fix — removed incorrect endpoint nudge",]},
  {v:"v5.4",date:"Apr 2026",items:["Arrow tip flush fix: endpoint nudged INTO node so arrowhead is visually flush",
    "Description placeholder no longer shown twice (removed duplicate from node body)",
    "Icon grid uses CSS auto-fill — no more trailing empty gap in last row",]},
  {v:"v5.3",date:"Apr 2026",items:["Compact sidebar redesigned: narrower 136px panel, categories preserved, search works in all modes",
    "Arrow gap fix: markerEnd nudged slightly inward so arrowhead is flush with node edge",
    "Arrow bidirectional start correctly pulled forward by markerWidth×strokeWidth",
    "Icon sidebar tooltip shown in compact mode too",]},
  {v:"v5.2",date:"Apr 2026",items:["Arrow endpoint pull fixed: markerEnd no longer creates gap, markerStart correctly offset",
    "Compact sidebar mode now works — fixed out-of-scope state call bug",
    "Node library title no longer truncates in compact/icon modes",
    "Note content inline editable directly on canvas — click ✎ to edit",
    "Bidirectional arrow endpoints now correctly clear both node borders",
    "Node header redesigned: title + description in header, type label at right-bottom",
    "Comment 💬 and Collapse ⊟ icons share one row, no overlap",
    "Pencil ✎ icons on title, description, note title, and note content",
    "Inline note title editing without opening popup",
    "Changelog now maintained automatically in every version",]},
  {v:"v5.0",date:"Apr 2026",items:["Bidirectional arrows correctly show both arrowheads (auto-start-reverse)",
    "Inline text editing: pencil icon on title and description (F2 to rename)",
    "Keyboard shortcuts: E opens node popup, N adds note, F2 renames",
    "Compact sidebar mode: multi-icon dense grid",
    "Node type badge moved to right-bottom, less distracting",
    "Node description displayed directly under title",
    "Export/Import .nonote bundle format",
    "Focus mode activates on node click",
    "Resize snap guides",
    "Notes on node: expand per title, expand all button",
    "Quick add note button on node hover",]},
  {v:"v4.46–4.47",date:"2026",items:["Recursive subtree auto-layout (no overlapping nodes)",
    "5 layout directions: L→R, T→B, R→L, B→T, Radial",
    "Layout direction picker dropdown",
    "Popup closes on canvas click",
    "Absolute layer positions eliminate X-axis overlap",]},
  {v:"v4.42–4.45",date:"2026",items:["Complete search rewrite — searches all node data including note titles",
    "Edge routing: smart right→left preference for horizontal layouts",
    "Endpoint drag: slide t-offset along side, reset button",
    "Left-to-right tree layout",]},
  {v:"v4.38–4.41",date:"2026",items:["Canvas area restored + renderEdges/renderNodes helpers",
    "Node Library: collapse, icon-only, dense modes",
    "5-direction auto layout (LR/TB/RL/BT/Radial)",
    "Smart edge router with bestSides()",
    "Improved search covering note titles and descriptions",]},
  {v:"v4.33–4.37",date:"2026",items:["Multi-note per node (array of notes)",
    "Rich text editor with formatting toolbar",
    "Sensitive data toggle on notes (redacted in LLM export)",
    "Inline node editor popup on double-click (4 tabs)",
    "Node type picker in popup",
    "POPUP / PANEL toggle for properties mode",
    "Redesigned 2-row topbar with functional grouping",
    "Command-palette search overlay",]},
  {v:"v4.25–4.32",date:"2026",items:["Right-click context menu",
    "Snap-to-grid (Shift+drag)",
    "Alignment guides during drag",
    "Status dots on collapsed nodes",
    "Template library (Homelab, Microservices, Mind Map)",
    "Comment pins with threaded sidebar",
    "15 connection styles",
    "Focus mode (dims non-active nodes)",
    "Quick capture (Space bar)",
    "Ctrl+D duplicate",]},
  {v:"v4.0–4.24",date:"2025–2026",items:["Full-stack app: Node.js + PostgreSQL + Redis + Docker",
    "60+ node types across 9 categories",
    "Collision prevention with AABB detection",
    "Anchor system for connection endpoints",
    "Version history with restore",
    "LLM export and AI Chat panel",
    "Custom node properties and themes",
    "PNG export",]},
];


// Single source of truth for current version — always the first entry in CHANGELOG
export const CURRENT_VERSION = CHANGELOG[0].v;
