import { FileText,Type,User,RefreshCw,Folder,GitBranch,MessageSquare,Lightbulb,Pin,Brain,
  BookOpen,Quote,AlignLeft,HelpCircle,CheckCircle,AlertTriangle,Sparkles,Code2,Square,
  ClipboardList,Target,Flag,Clock,StopCircle,Play,XCircle,CheckCircle2,ExternalLink,
  BookMarked,Paperclip,Layers,Bookmark,Calculator,Router,Network,Shield,Scale,Lock,Wifi,
  Tv,Globe,Tag,Repeat,LogIn,ShieldCheck,GitMerge,Map,Building2,Navigation,Shuffle,Zap,
  Radio,AtSign,Search,Timer,Key,LayoutGrid,Eye,Activity,TestTube,Monitor,Laptop,Cpu,
  Tv2,Terminal,Server,Globe2,Settings,Database,Archive,Mail,Printer,HardDrive,
  FolderArchive,Disc,ArchiveRestore,Film,Smartphone,Tablet,CircuitBoard,Binary,Waves,
  Thermometer,Camera,Factory,DoorOpen,Wind,Cloud,Braces,ListOrdered,Share2,Package,
  Hexagon,Box,ArrowUpDown,PackageOpen,Link2,Library,Power,Puzzle,Gauge,MessageCircle,
  BellRing,ShieldOff,LockKeyhole,ScanSearch,Ban,
  Boxes,AppWindow,Component,Layers2,Container } from "lucide-react";

// ── Node type registry ────────────────────────────────────────
export const NT = {
  // ── General ──────────────────────────────────────────────────
  note:        { label:"Note",                color:"#FFD93D", icon:FileText,     cat:"General" },
  heading:     { label:"Heading",             color:"#6C63FF", icon:Type,         cat:"General" },
  user:        { label:"User / Person",       color:"#E91E63", icon:User,         cat:"General" },
  process:     { label:"Process",             color:"#9C27B0", icon:RefreshCw,    cat:"General" },
  group:       { label:"Group",               color:"#9E9E9E", icon:Folder,       cat:"General" },
  decision:    { label:"Decision",            color:"#FF9800", icon:GitBranch,    cat:"General" },
  annotation:  { label:"Annotation",          color:"#78909C", icon:MessageSquare,cat:"General" },
  // ── Notes ────────────────────────────────────────────────────
  idea:        { label:"Idea",                color:"#FFCA28", icon:Lightbulb,    cat:"Notes" },
  topic:       { label:"Topic",               color:"#AB47BC", icon:Pin,          cat:"Notes" },
  concept:     { label:"Concept",             color:"#7E57C2", icon:Brain,        cat:"Notes" },
  definition:  { label:"Definition",          color:"#5C6BC0", icon:BookOpen,     cat:"Notes" },
  quote:       { label:"Quote",               color:"#42A5F5", icon:Quote,        cat:"Notes" },
  summary:     { label:"Summary",             color:"#26C6DA", icon:AlignLeft,    cat:"Notes" },
  question:    { label:"Question",            color:"#FFA726", icon:HelpCircle,   cat:"Notes" },
  answer:      { label:"Answer",              color:"#66BB6A", icon:CheckCircle,  cat:"Notes" },
  warning:     { label:"Warning",             color:"#EF5350", icon:AlertTriangle,cat:"Notes" },
  tip:         { label:"Tip",                 color:"#26A69A", icon:Sparkles,     cat:"Notes" },
  codeblock:   { label:"Code Block",          color:"#78909C", icon:Code2,        cat:"Notes" },
  // ── Workflow (Workflow Audit feature) ──────────────────────────
  workflow_task: { label:"Workflow Task",     color:"#FF7043", icon:Repeat,       cat:"Workflow" },
  // ── Planning ─────────────────────────────────────────────────
  task:        { label:"Task",                color:"#29B6F6", icon:Square,       cat:"Planning" },
  checklist:   { label:"Checklist",           color:"#26C6DA", icon:ClipboardList,cat:"Planning" },
  goal:        { label:"Goal",                color:"#66BB6A", icon:Target,       cat:"Planning" },
  milestone:   { label:"Milestone",           color:"#FFA726", icon:Flag,         cat:"Planning" },
  deadline:    { label:"Deadline",            color:"#EF5350", icon:Clock,        cat:"Planning" },
  blocker:     { label:"Blocker",             color:"#F44336", icon:StopCircle,   cat:"Planning" },
  step:        { label:"Step",                color:"#8BC34A", icon:Play,         cat:"Planning" },
  problem:     { label:"Problem",             color:"#F44336", icon:XCircle,      cat:"Planning" },
  solution:    { label:"Solution",            color:"#4CAF50", icon:CheckCircle2, cat:"Planning" },
  // ── Knowledge ────────────────────────────────────────────────
  reference:   { label:"Reference",           color:"#78909C", icon:ExternalLink, cat:"Knowledge" },
  resource:    { label:"Resource",            color:"#26A69A", icon:BookMarked,   cat:"Knowledge" },
  evidence:    { label:"Evidence",            color:"#5C6BC0", icon:Paperclip,    cat:"Knowledge" },
  flashcard:   { label:"Flashcard",           color:"#EC407A", icon:Layers,       cat:"Knowledge" },
  bookmark:    { label:"Bookmark",            color:"#FF7043", icon:Bookmark,     cat:"Knowledge" },
  formula:     { label:"Formula",             color:"#42A5F5", icon:Calculator,   cat:"Knowledge" },
  // ── Network — Core ───────────────────────────────────────────
  router:      { label:"Router",              color:"#00BCD4", icon:Router,       cat:"Network" },
  switch:      { label:"Switch",              color:"#03A9F4", icon:Network,      cat:"Network" },
  firewall:    { label:"Firewall",            color:"#FF5722", icon:Shield,       cat:"Network" },
  loadbal:     { label:"Load Balancer",       color:"#26C6DA", icon:Scale,        cat:"Network" },
  vpn:         { label:"VPN Gateway",         color:"#42A5F5", icon:Lock,         cat:"Network" },
  ap:          { label:"Access Point",        color:"#29B6F6", icon:Wifi,         cat:"Network" },
  modem:       { label:"Modem",               color:"#4DD0E1", icon:Tv,           cat:"Network" },
  wanlink:     { label:"WAN Link",            color:"#0288D1", icon:Globe,        cat:"Network" },
  vlan:        { label:"VLAN",                color:"#0097A7", icon:Tag,          cat:"Network" },
  proxy:       { label:"Proxy",               color:"#00838F", icon:Repeat,       cat:"Network" },
  // ── Network — VPN & WAN ──────────────────────────────────────
  vpnclient:   { label:"VPN Client",          color:"#1565C0", icon:LogIn,        cat:"Network" },
  vpnserver:   { label:"VPN Server",          color:"#0D47A1", icon:ShieldCheck,  cat:"Network" },
  vpnconc:     { label:"VPN Concentrator",    color:"#1976D2", icon:GitMerge,     cat:"Network" },
  sdwan:       { label:"SD-WAN",              color:"#0277BD", icon:Map,          cat:"Network" },
  // ── Network — Routing Tiers ──────────────────────────────────
  corerouter:  { label:"Core Router",         color:"#006064", icon:Building2,    cat:"Network" },
  edgerouter:  { label:"Edge Router",         color:"#00838F", icon:Navigation,   cat:"Network" },
  l3switch:    { label:"L3 Switch",           color:"#007B83", icon:Shuffle,      cat:"Network" },
  poeswitch:   { label:"PoE Switch",          color:"#00ACC1", icon:Zap,          cat:"Network" },
  wlcont:      { label:"Wireless Controller", color:"#0097A7", icon:Radio,        cat:"Network" },
  // ── Network — Services ───────────────────────────────────────
  dhcpsrv:     { label:"DHCP Server",         color:"#00796B", icon:AtSign,       cat:"Network" },
  dnssrv:      { label:"DNS Server",          color:"#00695C", icon:Search,       cat:"Network" },
  ntpsrv:      { label:"NTP Server",          color:"#004D40", icon:Timer,        cat:"Network" },
  radiussrv:   { label:"RADIUS Server",       color:"#37474F", icon:Key,          cat:"Network" },
  patchpanel:  { label:"Patch Panel",         color:"#546E7A", icon:LayoutGrid,   cat:"Network" },
  nettap:      { label:"Network TAP",         color:"#607D8B", icon:Eye,          cat:"Network" },
  netmon:      { label:"Network Monitor",     color:"#78909C", icon:Activity,     cat:"Network" },
  honeypot:    { label:"Honeypot",            color:"#BF360C", icon:TestTube,     cat:"Network" },
  // ── Computers ────────────────────────────────────────────────
  desktop:     { label:"Desktop PC",          color:"#8D6E63", icon:Monitor,      cat:"Computers" },
  laptop:      { label:"Laptop",              color:"#A1887F", icon:Laptop,       cat:"Computers" },
  workstation: { label:"Workstation",         color:"#795548", icon:Cpu,          cat:"Computers" },
  thinclnt:    { label:"Thin Client",         color:"#6D4C41", icon:Tv2,          cat:"Computers" },
  kiosk:       { label:"Kiosk",               color:"#5D4037", icon:Terminal,     cat:"Computers" },
  // ── Servers ──────────────────────────────────────────────────
  server:      { label:"Server",              color:"#EF5350", icon:Server,       cat:"Servers" },
  webserver:   { label:"Web Server",          color:"#E53935", icon:Globe2,       cat:"Servers" },
  appserver:   { label:"App Server",          color:"#F44336", icon:Settings,     cat:"Servers" },
  dbserver:    { label:"DB Server",           color:"#C62828", icon:Database,     cat:"Servers" },
  fileserver:  { label:"File Server",         color:"#D32F2F", icon:Archive,      cat:"Servers" },
  mailserver:  { label:"Mail Server",         color:"#B71C1C", icon:Mail,         cat:"Servers" },
  printserver: { label:"Print Server",        color:"#FF8A80", icon:Printer,      cat:"Servers" },
  // ── Storage ──────────────────────────────────────────────────
  storage:     { label:"Storage",             color:"#607D8B", icon:HardDrive,    cat:"Storage" },
  nas:         { label:"NAS",                 color:"#546E7A", icon:FolderArchive,cat:"Storage" },
  san:         { label:"SAN",                 color:"#455A64", icon:Disc,         cat:"Storage" },
  backup:      { label:"Backup",              color:"#78909C", icon:ArchiveRestore,cat:"Storage"},
  tape:        { label:"Tape Library",        color:"#90A4AE", icon:Film,         cat:"Storage" },
  // ── Mobile & IoT ─────────────────────────────────────────────
  mobile:      { label:"Mobile / Phone",      color:"#66BB6A", icon:Smartphone,   cat:"Mobile & IoT" },
  tablet:      { label:"Tablet",              color:"#4CAF50", icon:Tablet,       cat:"Mobile & IoT" },
  rpi:         { label:"Raspberry Pi",        color:"#C62828", icon:CircuitBoard, cat:"Mobile & IoT" },
  arduino:     { label:"Arduino",             color:"#00979D", icon:Binary,       cat:"Mobile & IoT" },
  esp:         { label:"ESP32/8266",          color:"#E65100", icon:Waves,        cat:"Mobile & IoT" },
  sensor:      { label:"Sensor",              color:"#26A69A", icon:Thermometer,  cat:"Mobile & IoT" },
  camera:      { label:"IP Camera",           color:"#43A047", icon:Camera,       cat:"Mobile & IoT" },
  plc:         { label:"PLC",                 color:"#2E7D32", icon:Factory,      cat:"Mobile & IoT" },
  gateway:     { label:"IoT Gateway",         color:"#388E3C", icon:DoorOpen,     cat:"Mobile & IoT" },
  hvac:        { label:"HVAC",                color:"#1B5E20", icon:Wind,         cat:"Mobile & IoT" },
  // ── Cloud ────────────────────────────────────────────────────
  cloud:       { label:"Cloud",               color:"#29B6F6", icon:Cloud,        cat:"Cloud" },
  lambda:      { label:"Function / Lambda",   color:"#FF9100", icon:Braces,       cat:"Cloud" },
  queue:       { label:"Queue",               color:"#AB47BC", icon:ListOrdered,  cat:"Cloud" },
  cdn:         { label:"CDN",                 color:"#26A69A", icon:Share2,       cat:"Cloud" },
  s3:          { label:"Object Store",        color:"#FF6D00", icon:Package,      cat:"Cloud" },
  k8s:         { label:"Kubernetes",          color:"#326CE5", icon:Hexagon,      cat:"Cloud" },
  container:   { label:"Container",           color:"#2496ED", icon:Box,          cat:"Cloud" },
  apigateway:  { label:"API Gateway",         color:"#A100FF", icon:ArrowUpDown,  cat:"Cloud" },
  // ── Software ─────────────────────────────────────────────────
  software:    { label:"Software",            color:"#4CAF50", icon:PackageOpen,  cat:"Software" },
  api:         { label:"API",                 color:"#009688", icon:Link2,        cat:"Software" },
  database:    { label:"Database",            color:"#3F51B5", icon:Library,      cat:"Software" },
  service:     { label:"Service",             color:"#8BC34A", icon:Power,        cat:"Software" },
  microservice:{ label:"Microservice",        color:"#66BB6A", icon:Puzzle,       cat:"Software" },
  cache:       { label:"Cache",               color:"#FF7043", icon:Gauge,        cat:"Software" },
  broker:      { label:"Msg Broker",          color:"#7B1FA2", icon:MessageCircle,cat:"Software" },
  // ── Security ─────────────────────────────────────────────────
  ids:         { label:"IDS / IPS",           color:"#F44336", icon:BellRing,     cat:"Security" },
  waf:         { label:"WAF",                 color:"#E53935", icon:ShieldOff,    cat:"Security" },
  vault:       { label:"Vault / HSM",         color:"#B00020", icon:LockKeyhole,  cat:"Security" },
  siem:        { label:"SIEM",                color:"#C62828", icon:ScanSearch,   cat:"Security" },
  dlp:         { label:"DLP",                 color:"#D50000", icon:Ban,          cat:"Security" },
  // ── Homelab / Hypervisors ────────────────────────────────────
  proxmox:     { label:"Proxmox VE",          color:"#FF6C2F", icon:Layers,       cat:"Servers" },
  esxi:        { label:"VMware ESXi",         color:"#717CBD", icon:Cpu,          cat:"Servers" },
  hyperv:      { label:"Hyper-V Host",        color:"#0078D4", icon:Settings,     cat:"Servers" },
  unraid:      { label:"Unraid Server",       color:"#E67C1C", icon:LayoutGrid,   cat:"Servers" },
  truenas:     { label:"TrueNAS",             color:"#0095D5", icon:HardDrive,    cat:"Storage" },
  // ── Virtualisation & Containers ──────────────────────────────
  vm:          { label:"Virtual Machine",     color:"#8E24AA", icon:AppWindow,    cat:"Servers" },
  lxc:         { label:"LXC Container",       color:"#00897B", icon:Component,    cat:"Servers" },
  docker:      { label:"Docker Engine",       color:"#2496ED", icon:Container,    cat:"Software" },
  dockercont:  { label:"Docker Container",    color:"#1A7CC1", icon:Boxes,        cat:"Software" },
  compose:     { label:"Docker Compose",      color:"#003F8E", icon:Layers2,      cat:"Software" },
};

// Sidebar category display order — shared by NodeSidebar and InlineNodeEditor
export const SIDEBAR_CATS = ["Notes","Planning","Workflow","Knowledge","General","Network","Computers","Servers","Storage","Mobile & IoT","Cloud","Software","Security"];

// ── Default properties per node type ────────────────────────────
export const DP = {
  workflow_task:{Frequency:"Weekly",Duration:"15 min",Tools:"",Automation:"Manual"},
  note:{Content:""},
  heading:{Level:"H1",Subtitle:""},
  user:{Role:"",Email:"",Team:""},
  process:{Step:"",Input:"",Output:""},
  group:{Description:""},
  decision:{Condition:"",Yes:"",No:""},
  annotation:{Reference:""},
  // Network
  router:{IP:"",Domain:"",Subnet:"",Gateway:"",Make:"",Model:"",Protocol:"BGP",Firmware:"",
    Ports:[
      {id:"eth0",label:"eth0",type:"LAN",connected:"",ip:""},
      {id:"eth1",label:"eth1",type:"WAN",connected:"",ip:""},
      {id:"eth2",label:"eth2",type:"LAN",connected:"",ip:""},
      {id:"eth3",label:"eth3",type:"LAN",connected:"",ip:""},
    ]},
  switch:{IP:"",Domain:"",Subnet:"",Make:"",Model:"",PortCount:"24",VLAN:"",Layer:"L2",
    Ports:[
      {id:"p1",label:"Port 1",type:"access",connected:"",vlan:""},
      {id:"p2",label:"Port 2",type:"access",connected:"",vlan:""},
      {id:"p3",label:"Port 3",type:"trunk",connected:"",vlan:""},
      {id:"p4",label:"Port 4",type:"trunk",connected:"",vlan:""},
    ]},
  firewall:{IP:"",Domain:"",Subnet:"",MAC:"",Make:"",Model:"",Rules:"",Zone:"",OS:""},
  loadbal:{Make:"",Model:"",Algorithm:"Round Robin",VIP:""},
  vpn:{IP:"",Protocol:"IPSec",Endpoint:"",Peer:"",Tunnel:""},
  ap:{IP:"",Make:"",Model:"",SSID:"",Band:"2.4GHz/5GHz",Channel:""},
  modem:{IP:"",Make:"",Model:"",ISP:"",Type:"Cable"},
  wanlink:{IP:"",Provider:"",Speed:"",Type:"MPLS",Redundant:"No"},
  vlan:{ID:"",Name:"",Subnet:"",Tagged:""},
  proxy:{Type:"Forward",IP:"",Port:"3128",Auth:""},
  // Computers
  desktop:{IP:"",Domain:"",Subnet:"",MAC:"",Make:"",Model:"",OS:"Windows 11",CPU:"",RAM:"",User:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"Ethernet",type:"Ethernet",connected:"",ip:""},{id:"usb1",label:"USB-A 1",type:"USB 3.0",connected:"",ip:""},{id:"usb2",label:"USB-A 2",type:"USB 3.0",connected:"",ip:""},{id:"hdmi",label:"HDMI",type:"HDMI",connected:"",ip:""}]},
  laptop:{IP:"",Make:"",Model:"",OS:"",CPU:"",RAM:"",User:"",Ports:[{id:"eth0",label:"Ethernet",type:"Ethernet",connected:"",ip:""},{id:"usbc1",label:"USB-C 1",type:"USB-C",connected:"",ip:""},{id:"usbc2",label:"USB-C 2",type:"Thunderbolt 4",connected:"",ip:""},{id:"hdmi",label:"HDMI",type:"HDMI",connected:"",ip:""}]},
  workstation:{IP:"",Make:"",Model:"",OS:"",CPU:"",RAM:"",GPU:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"Ethernet",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1",type:"Ethernet",connected:"",ip:""},{id:"usbc1",label:"Thunderbolt 1",type:"Thunderbolt 4",connected:"",ip:""},{id:"usbc2",label:"Thunderbolt 2",type:"Thunderbolt 4",connected:"",ip:""},{id:"dp1",label:"DisplayPort",type:"DisplayPort",connected:"",ip:""},{id:"hdmi",label:"HDMI",type:"HDMI",connected:"",ip:""}]},
  thinclnt:{IP:"",Make:"",Model:"",OS:"",Server:""},
  kiosk:{IP:"",Make:"",OS:"",Location:"",App:""},
  // Servers
  server:{IP:"",Domain:"",Subnet:"",MAC:"",Make:"",Model:"",OS:"",CPU:"",RAM:"",Role:"",Port:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"mgmt",label:"iDRAC/iLO",type:"iDRAC/iLO",connected:"",ip:""}]},
  webserver:{IP:"",Domain:"",Subnet:"",Software:"Nginx",Version:"",Port:"443",SSL:"Yes",CertExpiry:""},
  appserver:{IP:"",Runtime:"",Version:"",Port:"",Instances:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}]},
  dbserver:{IP:"",Engine:"PostgreSQL",Version:"",Port:"5432",RAM:""},
  fileserver:{IP:"",OS:"",Shares:"",Storage:"",Protocol:"SMB"},
  mailserver:{IP:"",Software:"",Domain:"",TLS:"Yes",Spam:""},
  printserver:{IP:"",Make:"",Model:"",Queue:"",Protocol:"IPP"},
  // Storage
  storage:{IP:"",Capacity:"",Type:"SSD",RAID:"",Interface:""},
  nas:{IP:"",Make:"",Model:"",Capacity:"",RAID:"",Shares:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1",type:"Ethernet",connected:"",ip:""}]},
  san:{IP:"",Make:"",Model:"",Capacity:"",FC:"",Protocol:"iSCSI"},
  backup:{IP:"",Software:"",Schedule:"",Retention:"",Target:""},
  tape:{IP:"",Make:"",Model:"",Capacity:"",Library:""},
  // Mobile & IoT
  mobile:{IP:"",Make:"",Model:"",OS:"",User:"",MDM:""},
  tablet:{IP:"",Make:"",Model:"",OS:"",User:""},
  rpi:{IP:"",Model:"Pi 4B",OS:"Raspberry Pi OS",RAM:"4GB",Role:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"Ethernet",type:"Ethernet",connected:"",ip:""},{id:"usb1",label:"USB-A 1",type:"USB 3.0",connected:"",ip:""},{id:"usb2",label:"USB-A 2",type:"USB 3.0",connected:"",ip:""},{id:"usbc",label:"USB-C Power",type:"USB-C",connected:"",ip:""},{id:"hdmi1",label:"HDMI 1",type:"HDMI",connected:"",ip:""}]},
  arduino:{IP:"",Model:"Uno",Firmware:"",Sensors:"",Protocol:""},
  esp:{IP:"",Model:"ESP32",Firmware:"",WiFi:"",Protocol:"MQTT"},
  sensor:{IP:"",Type:"",Protocol:"MQTT",Location:"",Unit:""},
  camera:{Make:"",Model:"",Resolution:"",Protocol:"RTSP",IP:""},
  plc:{IP:"",Make:"",Model:"",Protocol:"Modbus",IO:""},
  gateway:{IP:"",Make:"",Model:"",Protocol:"",Upstream:""},
  hvac:{IP:"",Make:"",Model:"",Zone:"",Protocol:"BACnet"},
  // Cloud
  cloud:{IP:"",Domain:"",Provider:"AWS",Region:"",Service:"",Account:""},
  lambda:{Runtime:"Node.js 20",Trigger:"",Memory:"256MB",Timeout:"30s"},
  queue:{Type:"SQS",MaxSize:"",DLQ:"",Delay:""},
  cdn:{Provider:"CloudFront",Origin:"",TTL:"3600",Geo:""},
  s3:{Provider:"AWS",Bucket:"",Region:"",Access:"Private"},
  k8s:{IP:"",Cluster:"",Namespace:"",Replicas:"",Version:""},
  container:{IP:"",Domain:"",Port:"",Image:"",Tag:"latest",Registry:""},
  apigateway:{IP:"",Provider:"AWS",Stage:"",Auth:"",Throttle:""},
  // Software
  software:{IP:"",Version:"",License:"",Port:"",Platform:""},
  api:{IP:"",Endpoint:"",Method:"REST",Auth:"Bearer",Version:"v1"},
  database:{IP:"",Domain:"",Port:"5432",Engine:"PostgreSQL",Schema:"",HA:"",Backup:""},
  service:{IP:"",URL:"",Status:"Running",Port:"",SLA:""},
  microservice:{IP:"",Language:"",Port:"",Version:"",Replicas:""},
  cache:{IP:"",Type:"Redis",Port:"6379",MaxMem:"",Eviction:"LRU"},
  broker:{IP:"",Type:"Kafka",Port:"9092",Topics:"",Retention:"7d"},
  // Security
  ids:{IP:"",Make:"",Model:"",Mode:"Inline",Ruleset:"Snort"},
  waf:{IP:"",Provider:"",Mode:"Block",Rules:"OWASP",SSL:"Yes"},
  vault:{Type:"HashiCorp Vault",Auth:"",Secrets:"",HA:""},
  siem:{Software:"",Sources:"",Retention:"90d",Alerts:""},
  dlp:{Provider:"",Mode:"",Channels:"",Policy:""},
  // Network extended
  vpnclient:{IP:"",Protocol:"WireGuard",Server:"",Port:"51820",Auth:""},
  vpnserver:{IP:"",Protocol:"WireGuard",Port:"51820",Clients:"",Subnet:""},
  vpnconc:{IP:"",Protocol:"IPSec",Tunnels:"",HA:"",Make:"",Model:""},
  sdwan:{IP:"",Make:"",Model:"",Uplinks:"",Policy:"",Orchestrator:""},
  corerouter:{IP:"",Make:"",Model:"",BGP_AS:"",Protocols:"OSPF/BGP",Interfaces:"",Ports:[{id:"eth0",label:"eth0",type:"WAN",connected:"",ip:""},{id:"eth1",label:"eth1",type:"LAN",connected:"",ip:""},{id:"eth2",label:"eth2",type:"LAN",connected:"",ip:""},{id:"sfp1",label:"SFP+ 1",type:"SFP+",connected:"",ip:""}]},
  edgerouter:{IP:"",Make:"",Model:"",ISP:"",NAT:"Yes",Protocols:"",Ports:[{id:"eth0",label:"eth0",type:"WAN",connected:"",ip:""},{id:"eth1",label:"eth1",type:"LAN",connected:"",ip:""},{id:"eth2",label:"eth2",type:"LAN",connected:"",ip:""}]},
  l3switch:{IP:"",Make:"",Model:"",VLANs:"",RoutingProtocol:"",PortCount:"",Ports:[{id:"p1",label:"Port 1",type:"trunk",connected:"",vlan:""},{id:"p2",label:"Port 2",type:"trunk",connected:"",vlan:""},{id:"up1",label:"Uplink 1",type:"uplink",connected:"",vlan:""},{id:"up2",label:"Uplink 2",type:"uplink",connected:"",vlan:""}]},
  poeswitch:{IP:"",Make:"",Model:"",PortCount:"24",PoEBudget:"",VLANs:"",Ports:[{id:"p1",label:"Port 1",type:"PoE",connected:"",vlan:""},{id:"p2",label:"Port 2",type:"PoE",connected:"",vlan:""},{id:"up1",label:"Uplink 1",type:"uplink",connected:"",vlan:""}]},
  wlcont:{IP:"",Make:"",Model:"",APs_Managed:"",SSID:"",Auth:"WPA3"},
  dhcpsrv:{IP:"",Scope:"",RangeStart:"",RangeEnd:"",Lease:"24h",DNS:""},
  dnssrv:{IP:"",Software:"BIND",Zones:"",Forwarders:"",DNSSEC:""},
  ntpsrv:{IP:"",Stratum:"",Upstream:"",Clients:""},
  radiussrv:{IP:"",Software:"FreeRADIUS",Port:"1812",Clients:"",Auth:"EAP-TLS"},
  patchpanel:{Location:"",Ports:"24",RackUnit:"",Label:""},
  nettap:{IP:"",Mode:"Passive",Make:"",Model:"",Speed:"",Mirror:""},
  netmon:{IP:"",Software:"",Protocol:"SNMP",Hosts:"",Dashboard:""},
  honeypot:{IP:"",Type:"Low-interaction",OS:"Decoy",Ports:"",Alert:""},
  // Homelab / Hypervisors
  proxmox:{IP:"",Domain:"",Subnet:"",MAC:"",Make:"",Model:"",CPU:"",RAM:"",Storage:"",PCIPassthrough:"",ClusterName:"",Services:[{id:"svc1",name:"Ubuntu VM",type:"VM",ip:"",port:"",status:"Running",image:"",os:"Ubuntu 22.04",memory:"4GB",cpu:"2",notes:""},{id:"svc2",name:"nginx",type:"LXC",ip:"",port:"80",status:"Running",image:"",os:"Debian",memory:"512MB",cpu:"1",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1",type:"Ethernet",connected:"",ip:""},{id:"mgmt",label:"IPMI/BMC",type:"iDRAC/iLO",connected:"",ip:""}]},
  esxi:{IP:"",Domain:"",Subnet:"",Make:"",Model:"",vCenter:"",Cluster:"",Version:"",CPU:"",RAM:"",DatastoreGB:"",Services:[{id:"svc1",name:"",type:"VM",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"vmnic0",label:"vmnic0",type:"Ethernet",connected:"",ip:""},{id:"vmnic1",label:"vmnic1",type:"Ethernet",connected:"",ip:""},{id:"mgmt",label:"IPMI/iDRAC",type:"iDRAC/iLO",connected:"",ip:""}]},
  hyperv:{IP:"",Domain:"",Subnet:"",Make:"",Model:"",WindowsVersion:"",vSwitches:"",Cluster:"",Services:[{id:"svc1",name:"",type:"VM",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1",type:"Ethernet",connected:"",ip:""},{id:"mgmt",label:"iDRAC/iLO",type:"iDRAC/iLO",connected:"",ip:""}]},
  unraid:{IP:"",Domain:"",Subnet:"",Make:"",Model:"",OS:"Unraid 7",CPU:"",RAM:"",ArraySize:"",Parity:"",Services:[{id:"svc1",name:"Ubuntu VM",type:"VM",ip:"",port:"",status:"Running",image:"",os:"Ubuntu 22.04",memory:"4GB",cpu:"2",notes:""},{id:"svc2",name:"nginx",type:"LXC",ip:"",port:"80",status:"Running",image:"",os:"Debian",memory:"512MB",cpu:"1",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1 (bonded)",type:"Ethernet",connected:"",ip:""},{id:"mgmt",label:"IPMI",type:"iDRAC/iLO",connected:"",ip:""}]},
  truenas:{IP:"",Domain:"",Subnet:"",Make:"",Model:"",Version:"",Capacity:"",RAID:"RAIDZ2",Shares:"",iSCSI:"",Services:[{id:"svc1",name:"",type:"App",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}],Ports:[{id:"eth0",label:"eth0",type:"Ethernet",connected:"",ip:""},{id:"eth1",label:"eth1",type:"Ethernet",connected:"",ip:""},{id:"hba1",label:"HBA 1",type:"HBA",connected:"",ip:""}]},
  // Virtualisation & Containers
  vm:{IP:"",OS:"Ubuntu 22.04",RAM:"4GB",CPU:"2",Disk:"50GB",Snapshot:"",Hypervisor:"",Status:"Running"},
  lxc:{IP:"",OS:"Debian",RAM:"512MB",CPU:"1",Disk:"10GB",Unprivileged:"Yes",Status:"Running"},
  docker:{IP:"",Version:"",Compose:"Yes",Swarm:"No",Networks:"bridge,host",Volumes:"",Services:[{id:"svc1",name:"",type:"Docker",ip:"",port:"",status:"Running",image:"",os:"",memory:"",cpu:"",notes:""}]},
  dockercont:{Image:"",Tag:"latest",Port:"",IP:"",Memory:"256MB",CPU:"1",Env:"",Volumes:"",Network:"bridge",Status:"Running"},
  compose:{File:"docker-compose.yml",Services:"",Networks:"",Volumes:"",Version:"3.8"},
  idea:{Content:"",Tags:"",Status:"New"},
  topic:{Content:"",Parent:"",Tags:""},
  concept:{Content:"",RelatedTo:"",Tags:""},
  definition:{Term:"",Definition:"",Source:""},
  quote:{Text:"",Author:"",Source:"",Page:""},
  summary:{Content:"",Source:"",KeyPoints:""},
  question:{Question:"",Context:"",Priority:"Medium"},
  answer:{Answer:"",Confidence:"High",References:""},
  warning:{Message:"",Severity:"Medium",Action:""},
  tip:{Content:"",Category:""},
  codeblock:{Language:"",Code:"",Description:""},
  // Planning
  task:{Title:"",Status:"Todo",Priority:"Medium",Assignee:"",Due:""},
  checklist:{Items:"",Done:"0",Total:"0"},
  goal:{Objective:"",KPI:"",Target:"",Due:""},
  milestone:{Name:"",Date:"",Status:"Upcoming",Owner:""},
  deadline:{Date:"",Item:"",Owner:"",Hard:"Yes"},
  blocker:{Issue:"",Impact:"High",Owner:"",Resolution:""},
  step:{Number:"",Action:"",Input:"",Output:""},
  problem:{Statement:"",Impact:"High",Cause:""},
  solution:{Approach:"",Effort:"Medium",Risk:"",Owner:""},
  // Knowledge
  reference:{URL:"",Title:"",Author:"",Date:""},
  resource:{Type:"Article",URL:"",Title:"",Tags:""},
  evidence:{Content:"",Source:"",Strength:"Strong"},
  flashcard:{Front:"",Back:"",Tags:"",Difficulty:"Medium"},
  bookmark:{URL:"",Title:"",Tags:"",Note:""},
  formula:{Expression:"",Variables:"",Unit:"",Notes:""},
};
